/**
 * Production-Grade Excel & CSV Exporter for Primary Slitter Production Plans
 * Replicates the authoritative GPAK Document GPAK/QR/PL/01 Layout
 * Strict Implementation of SRS Sections 40, 41, 77
 */

import * as XLSX from 'xlsx';
import { SlitterPlan, PlanningRun, VA05Order, PlanItem } from '../types';

/**
 * Generates an Excel workbook for a single Slitter Plan matching GPAK/QR/PL/01
 */
export function exportSinglePlanToExcel(plan: SlitterPlan): Uint8Array {
  const wb = XLSX.utils.book_new();
  const ws = createPlanWorksheet(plan);
  XLSX.utils.book_append_sheet(wb, ws, plan.plan_number.slice(0, 31));
  return XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
}

/**
 * Generates a complete Multi-Plan Planning Run Excel Workbook
 * Contains Summary Sheet + Individual Plan Sheets + Remaining Demand Sheet
 */
export function exportCompleteRunToExcel(
  run: PlanningRun,
  plans: SlitterPlan[],
  remainingOrders: VA05Order[]
): Uint8Array {
  const wb = XLSX.utils.book_new();

  // 1. Run Summary Sheet
  const summaryData = [
    ['PRIMARY SLITTER PLANNING RUN SUMMARY'],
    ['Run Number:', run.run_number, 'Film Grade:', run.film],
    ['Target Quantity (kg):', run.target_quantity_kg, 'Planned Quantity (kg):', run.planned_quantity_kg],
    ['Target Range (±5%):', run.target_min_kg ? `${run.target_min_kg} - ${run.target_max_kg} kg` : 'N/A', 'Target Deviation:', `${run.target_deviation_percent !== undefined ? run.target_deviation_percent : 0}%`],
    ['Remaining Quantity (kg):', run.remaining_quantity_kg, 'Plans Generated:', plans.length],
    ['Orders Completely Closed:', run.orders_closed_count, 'Orders Partially Fulfilled:', run.orders_partial_count],
    ['Trim Mode:', run.trim_rule_mode || 'NORMAL', 'Trim Limits:', `${run.min_trim_mm_used || 150} - ${run.max_trim_mm_used || 280} mm`],
    ['Status:', run.status, 'Generated By:', run.created_by],
    ['Created At:', run.created_at, 'Stop Reason:', run.stop_reason || 'N/A'],
    [],
    ['PLAN SUMMARY TABLE'],
    ['Plan No.', 'Film', 'UPS', 'Deckle (mm)', 'Slit Width (mm)', 'Trim (mm)', 'Length (m)', 'Reps', 'MR Length (m)', 'Planned Qty (kg)', 'Status'],
  ];

  plans.forEach(p => {
    summaryData.push([
      p.plan_number,
      p.film,
      p.ups,
      p.deckle_mm,
      p.total_slit_width_mm,
      p.trim_mm,
      p.length_m,
      p.repetitions,
      p.planned_mr_length_m,
      p.planned_quantity_kg,
      p.status,
    ]);
  });

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

  // 2. Individual Plan Sheets (One for each generated plan)
  plans.forEach((plan, idx) => {
    const sheetName = `Plan_${String(idx + 1).padStart(2, '0')}`;
    const wsPlan = createPlanWorksheet(plan);
    XLSX.utils.book_append_sheet(wb, wsPlan, sheetName);
  });

  // 3. Remaining Orders Sheet
  const remainingData: any[][] = [
    ['REMAINING DEMAND BACKLOG AFTER PLANNING RUN'],
    ['Film:', run.film, 'Run ID:', run.run_number],
    [],
    ['SO#', 'Item#', 'Customer', 'Width (mm)', 'Length (m)', 'Core', 'TS', 'Original Qty (kg)', 'Produced (kg)', 'Remaining Qty (kg)', 'Status', 'Delivery Date'],
  ];

  remainingOrders.forEach(o => {
    remainingData.push([
      o.sales_order,
      o.item_number,
      o.customer,
      o.width_mm,
      o.length_m,
      o.core,
      o.treatment_side,
      o.balance_qty,
      o.produced_qty,
      o.remaining_qty,
      o.status,
      o.delivery_date || '',
    ]);
  });

  const wsRemaining = XLSX.utils.aoa_to_sheet(remainingData);
  XLSX.utils.book_append_sheet(wb, wsRemaining, 'Remaining Demand');

  return XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
}

export interface ConsolidatedPlanItemRow {
  key: string;
  id: string;
  position_label: string;
  station: 'SIDE_A' | 'SIDE_B' | 'MIXED';
  station_label: string;
  sales_order: string;
  item_number: number | string;
  customer: string;
  film: string;
  length_m: number;
  core: number | string;
  treatment_side: string;
  width_mm: number;
  total_weight_kg: number;
  size_mm: number;
  ups: number;
  deckle_mm: number;
  reels: number;
  weight_per_pack_kg: number;
  is_closed: boolean;
  is_future_replacement?: boolean;
  start_pack?: number;
  active_packs?: number;
  replacement_instruction?: string;
  raw_items: PlanItem[];
}

export function formatNumberRangeList(nums: number[]): string {
  if (!nums || nums.length === 0) return '';
  const sorted = Array.from(new Set(nums.filter(n => typeof n === 'number' && !isNaN(n)))).sort((a, b) => a - b);
  if (sorted.length === 0) return '';
  if (sorted.length === 1) return `${sorted[0]}`;

  const ranges: string[] = [];
  let start = sorted[0];
  let end = sorted[0];

  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i] === end + 1) {
      end = sorted[i];
    } else {
      ranges.push(start === end ? `${start}` : `${start}–${end}`);
      start = sorted[i];
      end = sorted[i];
    }
  }
  ranges.push(start === end ? `${start}` : `${start}–${end}`);
  return ranges.join(', ');
}

/**
 * Consolidates plan items sharing the same Sales Order, Item Number, Customer, Size, Core, Treatment & Length.
 * Combines individual UPS cuts into a single unified execution row with total UPS count, total deckle, and total weight.
 */
export function consolidatePlanItems(items: PlanItem[] = []): ConsolidatedPlanItemRow[] {
  if (!items || items.length === 0) return [];

  const map = new Map<string, PlanItem[]>();

  items.forEach(item => {
    // FUTURE SHIFT only when engine marked a true size-change replacement.
    // start_pack > 1 alone (same size, different customer/SO/item) is NOT future shift.
    const isFuture = !!item.is_future_replacement;
    const soClean = (item.sales_order || '').trim();
    const itemNumClean = `${item.item_number || ''}`.trim();
    const custClean = (item.customer || '').trim();
    const w = Number(item.width_mm || 0);
    const l = Number(item.length_m || 0);
    const c = `${item.core || ''}`.trim();
    const ts = (item.treatment_side || '').trim();

    const key = `${soClean}__${itemNumClean}__${custClean}__${w}__${l}__${c}__${ts}__${isFuture ? '1' : '0'}`;
    if (!map.has(key)) {
      map.set(key, []);
    }
    map.get(key)!.push(item);
  });

  const consolidated: ConsolidatedPlanItemRow[] = [];

  map.forEach((groupedItems, key) => {
    const first = groupedItems[0];
    const isFuture = !!first.is_future_replacement;

    // Total UPS sum: only active items count towards initial active UPS
    const totalUps = isFuture ? 0 : groupedItems.reduce((sum, it) => {
      const up = it.is_future_replacement ? 0 : (it.initial_ups !== undefined ? it.initial_ups : (it.ups || 1));
      return sum + up;
    }, 0);

    // Sum Total Weight
    const totalWeightKg = Number(groupedItems.reduce((sum, it) => sum + (it.total_weight_kg || 0), 0).toFixed(2));

    // Sum Reels
    const totalReels = groupedItems.reduce((sum, it) => sum + (it.reels || 0), 0);

    // Sum Weight per pack
    const totalWeightPerPack = Number(groupedItems.reduce((sum, it) => sum + (it.weight_per_pack_kg || 0), 0).toFixed(2));

    // Deckle (mm)
    const deckleMm = isFuture ? 0 : (first.width_mm * totalUps);

    // Collect all Positions and Arm numbers
    const allPositions: number[] = [];
    const allArms: number[] = [];

    groupedItems.forEach((it, idx) => {
      let foundPosInLabel = false;
      let foundArmInLabel = false;

      if (it.position_label) {
        const posMatch = it.position_label.match(/Pos\s*([0-9,\s–-]+)/i);
        const armMatch = it.position_label.match(/Arm\s*([0-9,\s–-]+)/i);

        if (posMatch) {
          foundPosInLabel = true;
          const matchedStr = posMatch[1];
          const chunks = matchedStr.split(/[,]/);
          chunks.forEach(ch => {
            const range = ch.trim().split(/[–-]/);
            if (range.length === 2) {
              const rStart = parseInt(range[0].trim(), 10);
              const rEnd = parseInt(range[1].trim(), 10);
              if (!isNaN(rStart) && !isNaN(rEnd)) {
                for (let n = rStart; n <= rEnd; n++) allPositions.push(n);
              }
            } else if (range.length === 1) {
              const single = parseInt(range[0].trim(), 10);
              if (!isNaN(single)) allPositions.push(single);
            }
          });
        }

        if (armMatch) {
          foundArmInLabel = true;
          const matchedStr = armMatch[1];
          const chunks = matchedStr.split(/[,]/);
          chunks.forEach(ch => {
            const range = ch.trim().split(/[–-]/);
            if (range.length === 2) {
              const rStart = parseInt(range[0].trim(), 10);
              const rEnd = parseInt(range[1].trim(), 10);
              if (!isNaN(rStart) && !isNaN(rEnd)) {
                for (let n = rStart; n <= rEnd; n++) allArms.push(n);
              }
            } else if (range.length === 1) {
              const single = parseInt(range[0].trim(), 10);
              if (!isNaN(single)) allArms.push(single);
            }
          });
        }
      }

      if (!foundPosInLabel) {
        if (it.positions && it.positions.length > 0) {
          it.positions.forEach(p => allPositions.push(p));
        } else if (it.position !== undefined) {
          allPositions.push(it.position);
        }
      }

      if (!foundArmInLabel && it.position !== undefined) {
        allArms.push(it.position);
      }
    });

    const posRangeStr = formatNumberRangeList(allPositions);
    const armRangeStr = formatNumberRangeList(allArms);

    let posLabel = first.position_label || `${first.position || 1}`;
    if (posRangeStr && armRangeStr && posRangeStr !== armRangeStr) {
      posLabel = `Pos ${posRangeStr} (Arms ${armRangeStr})`;
    } else if (posRangeStr) {
      posLabel = `Pos ${posRangeStr}`;
    } else if (armRangeStr) {
      posLabel = `Arm ${armRangeStr}`;
    }

    // Stations
    const countA = groupedItems.filter(it => (it.station || (it.position <= 8 ? 'SIDE_A' : 'SIDE_B')) === 'SIDE_A').length;
    const countB = groupedItems.filter(it => (it.station || (it.position <= 8 ? 'SIDE_A' : 'SIDE_B')) === 'SIDE_B').length;

    let station: 'SIDE_A' | 'SIDE_B' | 'MIXED' = 'SIDE_A';
    let stationLabel = 'SIDE A';

    if (countA > 0 && countB === 0) {
      station = 'SIDE_A';
      stationLabel = 'SIDE A';
    } else if (countB > 0 && countA === 0) {
      station = 'SIDE_B';
      stationLabel = 'SIDE B';
    } else if (countA > 0 && countB > 0) {
      station = 'MIXED';
      stationLabel = `A: ${countA} | B: ${countB}`;
    }

    consolidated.push({
      key,
      id: first.id,
      position_label: posLabel,
      station,
      station_label: stationLabel,
      sales_order: first.sales_order,
      item_number: first.item_number,
      customer: first.customer,
      film: first.film,
      length_m: first.length_m,
      core: first.core,
      treatment_side: first.treatment_side,
      width_mm: first.width_mm,
      total_weight_kg: totalWeightKg,
      size_mm: first.width_mm,
      ups: totalUps,
      deckle_mm: deckleMm,
      reels: totalReels,
      weight_per_pack_kg: totalWeightPerPack,
      is_closed: groupedItems.every(it => it.is_closed),
      is_future_replacement: isFuture,
      start_pack: first.start_pack,
      active_packs: first.active_packs,
      replacement_instruction: first.replacement_instruction || (isFuture && first.start_pack ? `Starts after Pack ${first.start_pack - 1}` : undefined),
      raw_items: groupedItems,
    });
  });

  return consolidated;
}

/**
 * Creates a worksheet with the exact GPAK/QR/PL/01 Primary Slitter Layout
 */
/**
 * GPAK/QR/PL/01 Machine Plan sheet — layout locked to factory template
 * (MACHINE PLANSMP-PS1-030726-B.xlsx reference).
 * Columns A–R (18). Header rows 1–6, table from row 7–8, data, TOTAL, notes.
 */
function createPlanWorksheet(plan: SlitterPlan): XLSX.WorkSheet {
  const COLS = 18;
  const pad = (row: any[]): any[] => {
    const r = row.slice(0, COLS);
    while (r.length < COLS) r.push('');
    return r;
  };
  const emptyRow = () => pad([]);
  /** Blank body row with TOTAL-column zeros (factory template style) */
  const blankDataRow = () => {
    const r = emptyRow();
    r[11] = 0; // L DECKLE
    r[12] = 0; // M REELS
    r[13] = 0; // N WT/PACK
    r[14] = 0; // O TOT.WT
    return r;
  };

  const consolidatedItems = consolidatePlanItems(plan.items || []);
  const initialActiveRows = consolidatedItems.filter(it => !it.is_future_replacement);
  const initialActiveUps = initialActiveRows.reduce((sum, it) => sum + (it.ups || 0), 0);
  const initialActiveSlitWidth = initialActiveRows.reduce((sum, it) => sum + (it.deckle_mm || 0), 0);
  const initialActiveReels = initialActiveRows.reduce((sum, it) => sum + (it.reels || 0), 0);
  const initialActiveWeightPerPack = Number(
    initialActiveRows.reduce((sum, it) => sum + (it.weight_per_pack_kg || 0), 0).toFixed(3)
  );
  const initialActiveWeight = Number(
    initialActiveRows.reduce((sum, it) => sum + (it.total_weight_kg || 0), 0).toFixed(3)
  );

  const displayPlanNumber = (plan.plan_number || '')
    .replace(/\bPS01\b/g, 'PS')
    .replace(/^PS01-/g, 'PS-');
  const shortPlanId = displayPlanNumber.replace(/^PS-?/i, '').slice(0, 20);
  const thickness = Number(plan.thickness_micron || 0);
  const lengthM = Number(plan.length_m || 0);
  const density = Number(plan.density || 0);
  const deckle = Number(plan.deckle_mm || 10400);
  const utilized = Number(plan.total_slit_width_mm || initialActiveSlitWidth || 0);
  const trimMm = Number(plan.trim_mm ?? (deckle - utilized));
  const remainingWeb = Number((utilized - deckle).toFixed(2)); // factory sample uses negative when over
  const wasteFrac = deckle > 0 ? trimMm / deckle : 0;
  // Factory diameter: 1.14 * sqrt(T * L)
  const reelDiameter = thickness > 0 && lengthM > 0
    ? Number((1.14 * Math.sqrt(thickness * lengthM)).toFixed(10))
    : '';
  const millRollWt = Number(plan.mill_roll_weight_kg ?? 0);
  const trimWt = Number(plan.trim_weight_kg ?? 0);
  const reps = Number(plan.repetitions || 1);
  const allowedTrim = Number(plan.allowed_trim_mm ?? 180);
  const upsTotal = initialActiveUps || Number(plan.ups || 0);
  const rej = plan.rejection_material || '';
  const docLine = `Doc Ref: ${plan.doc_ref || 'GPAK/QR/PL/01'}                              Rev No: ${plan.rev_no ?? 0}                                                            Issue Date: ${plan.issue_date || ''}`;

  const rows: any[][] = [];
  const merges: XLSX.Range[] = [];

  // —— Row 1 ——
  rows.push(pad([
    displayPlanNumber, '', '', '', '', '', '',
    'PS01', 'PRIMARY SLITTER 1', '', '', '',
    'Trim(mm)', '', trimMm,
    'Thickness', '', thickness,
  ]));
  merges.push({ s: { r: 0, c: 0 }, e: { r: 0, c: 6 } }); // A1:G1
  merges.push({ s: { r: 0, c: 8 }, e: { r: 0, c: 11 } }); // I1:L1
  merges.push({ s: { r: 0, c: 12 }, e: { r: 0, c: 13 } }); // M1:N1
  merges.push({ s: { r: 0, c: 15 }, e: { r: 0, c: 16 } }); // P1:Q1

  // —— Row 2 ——
  rows.push(pad([
    'FILM', plan.film || '', '', '', '', '', '',
    "Mill Rolls' Wt.(kgs)", '', '', millRollWt, '',
    'Trim Wt. (kgs)', '', trimWt,
    'Density', '', density,
  ]));
  merges.push({ s: { r: 1, c: 1 }, e: { r: 1, c: 6 } }); // B2:G2
  merges.push({ s: { r: 1, c: 7 }, e: { r: 1, c: 9 } }); // H2:J2
  merges.push({ s: { r: 1, c: 10 }, e: { r: 1, c: 11 } }); // K2:L2
  merges.push({ s: { r: 1, c: 12 }, e: { r: 1, c: 13 } }); // M2:N2
  merges.push({ s: { r: 1, c: 15 }, e: { r: 1, c: 16 } }); // P2:Q2

  // —— Row 3 ——
  rows.push(pad([
    'LENGTH', lengthM, '', '', '', '', '',
    'Reel Diameter (mm)', '', '', reelDiameter, '',
    'Waste (%)', '', wasteFrac,
    'Allowed Trim', '', allowedTrim,
  ]));
  merges.push({ s: { r: 2, c: 1 }, e: { r: 2, c: 6 } });
  merges.push({ s: { r: 2, c: 7 }, e: { r: 2, c: 9 } });
  merges.push({ s: { r: 2, c: 10 }, e: { r: 2, c: 11 } });
  merges.push({ s: { r: 2, c: 12 }, e: { r: 2, c: 13 } });
  merges.push({ s: { r: 2, c: 15 }, e: { r: 2, c: 16 } });

  // —— Row 4 ——
  rows.push(pad([
    'TIME', '', '', '', '', '', '',
    'Time/Pack (min)', '', '', '', '',
    'Utilized Web', '', utilized,
    'Ups', '', upsTotal,
  ]));
  merges.push({ s: { r: 3, c: 1 }, e: { r: 3, c: 6 } });
  merges.push({ s: { r: 3, c: 7 }, e: { r: 3, c: 9 } });
  merges.push({ s: { r: 3, c: 10 }, e: { r: 3, c: 11 } });
  merges.push({ s: { r: 3, c: 12 }, e: { r: 3, c: 13 } });
  merges.push({ s: { r: 3, c: 15 }, e: { r: 3, c: 16 } });

  // —— Row 5 ——
  rows.push(pad([
    'REPS.', reps, '', '', '', '', '',
    'Planned MR Length', '', '', Number(plan.planned_mr_length_m ?? lengthM * reps), '',
    'Remaining Web', '', remainingWeb,
    'Rej Material', '', rej,
  ]));
  merges.push({ s: { r: 4, c: 1 }, e: { r: 4, c: 6 } });
  merges.push({ s: { r: 4, c: 7 }, e: { r: 4, c: 9 } });
  merges.push({ s: { r: 4, c: 10 }, e: { r: 4, c: 11 } });
  merges.push({ s: { r: 4, c: 12 }, e: { r: 4, c: 13 } });
  merges.push({ s: { r: 4, c: 15 }, e: { r: 4, c: 16 } });

  // —— Row 6 ——
  rows.push(pad([
    'Web.', '', deckle, '', '', '', '',
    'Mill Rolls Length', '', '', '', '',
    'Per Up', '', '',
    docLine, '', '',
  ]));
  merges.push({ s: { r: 5, c: 0 }, e: { r: 5, c: 1 } }); // A6:B6
  merges.push({ s: { r: 5, c: 2 }, e: { r: 5, c: 6 } }); // C6:G6
  merges.push({ s: { r: 5, c: 7 }, e: { r: 5, c: 9 } });
  merges.push({ s: { r: 5, c: 10 }, e: { r: 5, c: 11 } });
  merges.push({ s: { r: 5, c: 12 }, e: { r: 5, c: 13 } });
  merges.push({ s: { r: 5, c: 15 }, e: { r: 5, c: 17 } }); // P6:R6 doc

  // —— Row 7: instruction + sub-headers ——
  rows.push(pad([
    'USE CORE SIZE AND SLIT LENGTH AS MENTIONED ABOVE WITH EACH WIDTH',
    '', '', '', '', '', '', '', '', '', '',
    'TOTAL ', 'TOTAL ', 'WT/PACK', 'TOT.WT.',
    '', '', '',
  ]));

  // —— Row 8: column headers ——
  rows.push(pad([
    'SO#', 'Item#', 'CUSTOMER', 'Length', 'Core', 'TS', 'Width',
    'REELS', 'WEIGHT', 'SIZE(mm)', 'UPS', 'DECKLE', 'REELS', '(KGS)', '(KGS)',
    'Starting Time', '', '',
  ]));
  merges.push({ s: { r: 7, c: 15 }, e: { r: 7, c: 17 } }); // P8:R8

  // Pre-allocate template blank rows (factory sheet style) then fill data
  const MIN_BODY = 22;
  const bodyStart = rows.length; // row index 8 in 0-based = Excel row 9

  // Floor-log labels on the right (column P) at template positions
  const floorLabels: Record<number, string> = {
    0: 'Starting Time',       // Excel row 9 — already on header row 8
    2: 'Completion Time',     // ~row 11
    6: 'Duration (hrs)',      // ~row 15
    11: 'Repitions Completed',
    15: 'Rejection',
    18: 'Consumed Length',
  };

  // Build data rows from consolidated items
  const dataRows: any[][] = [];
  consolidatedItems.forEach(item => {
    const isFuture = !!item.is_future_replacement;
    const ups = isFuture ? 0 : (item.ups || 0);
    const deckleMm = isFuture ? 0 : (item.deckle_mm || 0);
    const reels = item.reels || 0;
    const wtPack = isFuture
      ? 0
      : (item.weight_per_pack_kg > 0
          ? Number(item.weight_per_pack_kg.toFixed(3))
          : Number(((item.total_weight_kg || 0) / Math.max(reps, 1)).toFixed(3)));
    const totWt = Number((item.total_weight_kg || 0).toFixed(3));
    const so = String(item.sales_order || '').replace(/^SO#/i, '');
    dataRows.push(pad([
      so,
      item.item_number,
      item.customer,
      item.length_m,
      item.core,
      item.treatment_side,
      item.width_mm,
      reels,
      totWt,
      item.width_mm,
      isFuture ? '' : ups,
      isFuture ? 0 : deckleMm,
      isFuture ? 0 : reels,
      isFuture ? 0 : wtPack,
      isFuture ? 0 : totWt,
      '', '', '',
    ]));
  });

  // Body: interleave blanks to reach MIN_BODY then append remaining data
  // Factory template has blanks first then data; we put all data then pad with blanks
  const body: any[][] = [];
  dataRows.forEach(r => body.push(r));
  while (body.length < MIN_BODY) body.push(blankDataRow());

  body.forEach((r, i) => {
    if (floorLabels[i] && !r[15]) r[15] = floorLabels[i];
    rows.push(r);
  });

  // TOTAL row (factory: H=total reels, I=total weight, J=TOTAL, K=ups, L=deckle sum, M=reels, N/O=wt)
  const totalReels = initialActiveReels || consolidatedItems.reduce((s, it) => s + (it.reels || 0), 0);
  const totalWt = initialActiveWeight || Number(plan.order_weight_kg || 0);
  rows.push(pad([
    '', '', '', '', '', '', '',
    totalReels,
    totalWt,
    'TOTAL',
    initialActiveUps,
    initialActiveSlitWidth || utilized,
    totalReels,
    totalWt,
    totalWt,
    shortPlanId,
    '', '',
  ]));

  // Change / operator instruction row
  let changeText = '';
  if (plan.changes && plan.changes.length > 0) {
    changeText = plan.changes.map(ch => ch.instruction).filter(Boolean).join(' | ');
  }
  if (!changeText) {
    changeText = 'Standard slitting execution. No in-run knife shift.';
  }
  const changeRowIdx = rows.length;
  rows.push(pad([changeText]));
  merges.push({ s: { r: changeRowIdx, c: 0 }, e: { r: changeRowIdx, c: 8 } }); // A:I like sample A32:I32

  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!merges'] = merges;
  // Column widths close to factory template
  ws['!cols'] = [
    { wch: 12 }, // A SO#
    { wch: 8 },  // B Item
    { wch: 36 }, // C Customer
    { wch: 10 }, // D Length
    { wch: 6 },  // E Core
    { wch: 5 },  // F TS
    { wch: 8 },  // G Width
    { wch: 8 },  // H REELS
    { wch: 12 }, // I WEIGHT
    { wch: 10 }, // J SIZE
    { wch: 6 },  // K UPS
    { wch: 10 }, // L DECKLE
    { wch: 8 },  // M REELS
    { wch: 10 }, // N WT/PACK
    { wch: 12 }, // O TOT.WT
    { wch: 14 }, // P floor logs
    { wch: 10 },
    { wch: 10 },
  ];
  (ws as any)['!freeze'] = { xSplit: 0, ySplit: 8 };

  return ws;
}

/**
 * Triggers file download in browser
 */
export function downloadExcelBuffer(buffer: Uint8Array, filename: string) {
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
