/**
 * GPAK SS <-> PS01 Feasibility Handshake Adapter
 * 
 * CRITICAL ARCHITECTURAL CONSTRAINTS:
 * - PS01 Primary Slitter optimizer is 100% FROZEN.
 * - This adapter acts as a non-invasive bridge to evaluate whether candidate
 *   Jumbo Roll requirements generated by SS are physically and mathematically
 *   manufacturable on PS01 (10,400 mm mother deckle, 140-250 mm normal trim, duplex balance).
 * - SS Jumbo Width Limits: 355 mm to 1720 mm (width < 355 or > 1720 is invalid).
 * - SS-side PS01 feasibility handshake evaluates 6 UPS through 16 UPS (1–5 UPS strictly forbidden).
 * - Width Priority: Prefer jumbo widths as close to 1720 mm as practical (preferred, not mandatory).
 * - UPS Priority: Prefer minimum number of jumbo UPS positions (6 > 7 > ... > 16).
 * - Implements strict Priority Ordering for Trim Relaxation (Last Resort Only):
 *   Priority A: Normal SS trim (GREEN 11-35mm) + Normal PS01 rules (140-250mm) -> GREEN
 *   Priority B: Explore all viable combination permutations
 *   Priority C: SS Trim adjustment within [15, 40] mm -> YELLOW (MSL_TRIM_ADJUSTED)
 *   Priority D/E: Upstream PS01 Trim relaxation -> YELLOW (PS01_TRIM_RELAXED)
 *   Otherwise: RED (Infeasible)
 */

import { DEFAULT_PLANNING_RULES } from '../masterData';
import { VA05Order, SlitterPlan, PlanItem, PlanSegment } from '../../types';
import { generatePrimarySlitterPlans, OptimizationResult } from '../optimizer/deckleOptimizer';
import { SSJumboRequirement, JumboRequirement } from '../../types/ss';
import { resolveFilmDensity } from '../stuffing/filmDensities';

export type PS01HandshakeStatus = 'GREEN' | 'YELLOW' | 'RED';
export type TrimRelaxationType = 'NONE' | 'MSL_TRIM_ADJUSTED' | 'PS01_TRIM_RELAXED';

export interface PS01FeasibilityEvaluation {
  status: PS01HandshakeStatus;
  is_feasible: boolean;
  ps01_deckle_mm: number;
  jumbo_width_mm: number;
  ps01_ups: number;
  ps01_cut_combination: number[];
  ps01_total_width_mm: number;
  ps01_trim_mm: number;
  ps01_deckle_efficiency_percent: number;
  ps01_duplex_balanced: boolean;
  side_a_ups: number;
  side_b_ups: number;
  relaxation_type: TrimRelaxationType;
  relaxation_flag?: string;
  explanation: string;
}

export interface CandidateJumboProposal {
  film: string;
  thickness_micron: number;
  finished_widths: number[];
  msl_ups: number;
  target_msl_trim_mm: number;
  jumbo_width_mm: number;
  package_length_m: number;
  package_multiple: number;
  jumbo_length_m: number;
  diameter_mm: number;
  matching_orders: VA05Order[];
}

// Memoization caches for high-speed deterministic feasibility queries
const comboFeasibilityCache = new Map<string, PS01FeasibilityEvaluation>();
const singleFeasibilityCache = new Map<string, PS01FeasibilityEvaluation>();

/**
 * Evaluate multi-width PS01 combination feasibility (e.g. 6 to 16 jumbo widths)
 * Strictly enforces:
 * - 6–16 UPS evaluated (1–5 UPS strictly forbidden)
 * - SS Jumbo width limits: 355 mm to 1720 mm
 * - Standard PS01 trim for SS: 150–280 mm (GREEN)
 * - Relaxed PS01 trim: 281–500 mm (YELLOW)
 * - Trim < 150 mm or > 500 mm: RED
 */
export function evaluatePS01CombinationFeasibility(
  widths: number[],
  filmType: string = 'PLAIN_TRANSPARENT',
  thicknessMicron: number = 18
): PS01FeasibilityEvaluation {
  const cacheKey = `${widths.slice().sort().join(',')}_${filmType}_${thicknessMicron}`;
  const cached = comboFeasibilityCache.get(cacheKey);
  if (cached) return cached;

  const motherDeckle = DEFAULT_PLANNING_RULES.deckle_width_mm || 10400;
  // Factory standard for SS upstream PS01 jumbo manufacturing: 150–280 mm GREEN
  const normalMinTrim = 150;
  const normalMaxTrim = 280;
  const ps01Ups = widths.length;

  // Enforce SS upstream 6–16 UPS constraint
  if (ps01Ups < 6 || ps01Ups > 16) {
    const res: PS01FeasibilityEvaluation = {
      status: 'RED',
      is_feasible: false,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.round(widths.reduce((a, b) => a + b, 0) / (ps01Ups || 1)),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: widths.reduce((a, b) => a + b, 0),
      ps01_trim_mm: 0,
      ps01_deckle_efficiency_percent: 0,
      ps01_duplex_balanced: false,
      side_a_ups: 0,
      side_b_ups: 0,
      relaxation_type: 'NONE',
      explanation: `PS01 upstream jumbo manufacturing strictly forbids ${ps01Ups}-UPS for SS (allowed: 6–16 UPS; 1–5 UPS are strictly invalid)`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Check any individual width against SS valid limits (355–1720 mm)
  if (widths.some(w => w < 355 || w > 1720)) {
    const minW = Math.min(...widths);
    const maxW = Math.max(...widths);
    const res: PS01FeasibilityEvaluation = {
      status: 'RED',
      is_feasible: false,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.round(widths.reduce((a, b) => a + b, 0) / ps01Ups),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: widths.reduce((a, b) => a + b, 0),
      ps01_trim_mm: 0,
      ps01_deckle_efficiency_percent: 0,
      ps01_duplex_balanced: false,
      side_a_ups: 0,
      side_b_ups: 0,
      relaxation_type: 'NONE',
      explanation: `One or more jumbo widths (${minW < 355 ? `${minW} mm < 355 mm` : `${maxW} mm > 1720 mm`}) are outside SS valid range of 355–1720 mm`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  const totalSlitWidth = widths.reduce((a, b) => a + b, 0);
  const ps01Trim = motherDeckle - totalSlitWidth;
  const sideAUps = Math.ceil(ps01Ups / 2);
  const sideBUps = Math.floor(ps01Ups / 2);
  const isDuplexBalanced = Math.abs(sideAUps - sideBUps) <= 1 && sideAUps <= 8 && sideBUps <= 8;
  const efficiency = Number(((totalSlitWidth / motherDeckle) * 100).toFixed(2));
  const cutDesc = widths.join(' + ') + ` mm = ${totalSlitWidth} mm`;

  // Standard PS01 trim (150 - 280 mm) -> GREEN
  if (ps01Trim >= normalMinTrim && ps01Trim <= normalMaxTrim) {
    const res: PS01FeasibilityEvaluation = {
      status: 'GREEN',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.round(totalSlitWidth / ps01Ups),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: totalSlitWidth,
      ps01_trim_mm: ps01Trim,
      ps01_deckle_efficiency_percent: efficiency,
      ps01_duplex_balanced: isDuplexBalanced,
      side_a_ups: sideAUps,
      side_b_ups: sideBUps,
      relaxation_type: 'NONE',
      explanation: `${ps01Ups === 6 ? 'Preferred 6-UPS' : `${ps01Ups}-UPS`} multi-width jumbo pattern on PS01 (${cutDesc}, PS01 Trim: ${ps01Trim}mm within standard ${normalMinTrim}–${normalMaxTrim}mm)`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Relaxed PS01 trim (281 - 500 mm) -> YELLOW
  if (ps01Trim > normalMaxTrim && ps01Trim <= 500) {
    const res: PS01FeasibilityEvaluation = {
      status: 'YELLOW',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.round(totalSlitWidth / ps01Ups),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: totalSlitWidth,
      ps01_trim_mm: ps01Trim,
      ps01_deckle_efficiency_percent: efficiency,
      ps01_duplex_balanced: isDuplexBalanced,
      side_a_ups: sideAUps,
      side_b_ups: sideBUps,
      relaxation_type: 'PS01_TRIM_RELAXED',
      relaxation_flag: `NON-STANDARD PS01 TRIM: Upstream trim relaxed to ${ps01Trim} mm (standard: ${normalMinTrim}–${normalMaxTrim} mm) for ${ps01Ups}-UPS multi-width pattern`,
      explanation: `Feasible via PS01 Trim Relaxation (${ps01Ups}-UPS): ${cutDesc}, PS01 Trim = ${ps01Trim}mm within allowed relaxation envelope (281–500 mm)`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Infeasible (< 150 mm or > 500 mm) -> RED
  const redRes: PS01FeasibilityEvaluation = {
    status: 'RED',
    is_feasible: false,
    ps01_deckle_mm: motherDeckle,
    jumbo_width_mm: Math.round(totalSlitWidth / ps01Ups),
    ps01_ups: ps01Ups,
    ps01_cut_combination: widths,
    ps01_total_width_mm: totalSlitWidth,
    ps01_trim_mm: ps01Trim,
    ps01_deckle_efficiency_percent: efficiency,
    ps01_duplex_balanced: isDuplexBalanced,
    side_a_ups: sideAUps,
    side_b_ups: sideBUps,
    relaxation_type: 'NONE',
    explanation: `Cannot manufacture combination on PS01: ${cutDesc}, resulting in invalid trim of ${ps01Trim} mm (strictly requires 150–500 mm envelope; trim < 150 mm or > 500 mm is RED)`,
  };
  comboFeasibilityCache.set(cacheKey, redRes);
  return redRes;
}

/**
 * Perform non-invasive PS01 Feasibility Handshake for a proposed Jumbo Width
 * Evaluates 6–16 UPS, prioritizing minimum UPS and widths close to 1720 mm.
 */
export function evaluatePS01Feasibility(
  jumboWidthMm: number,
  film: string,
  thicknessMicron: number,
  finishedWidths: number[] = [],
  baseMslTrimMm: number = 25
): PS01FeasibilityEvaluation {
  const cacheKey = `${film}:${thicknessMicron}:${jumboWidthMm}:${finishedWidths.join(',')}:${baseMslTrimMm}`;
  const cached = singleFeasibilityCache.get(cacheKey);
  if (cached) return cached;

  const motherDeckle = DEFAULT_PLANNING_RULES.deckle_width_mm || 10400;
  // Factory standard for SS upstream PS01 jumbo manufacturing: 150–280 mm GREEN
  const normalMinTrim = 150;
  const normalMaxTrim = 280;

  // Enforce SS hard limits on Jumbo Width (355–1720 mm)
  if (jumboWidthMm < 355 || jumboWidthMm > 1720) {
    const res: PS01FeasibilityEvaluation = {
      status: 'RED',
      is_feasible: false,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 0,
      ps01_cut_combination: [],
      ps01_total_width_mm: 0,
      ps01_trim_mm: 0,
      ps01_deckle_efficiency_percent: 0,
      ps01_duplex_balanced: false,
      side_a_ups: 0,
      side_b_ups: 0,
      relaxation_type: 'NONE',
      explanation: `Jumbo width ${jumboWidthMm} mm is outside SS valid range of 355–1720 mm`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // -------------------------------------------------------------------------
  // PRIORITY 1: Evaluate 6 to 16 UPS with Standard PS01 Trim (150 - 280 mm -> GREEN)
  // Evaluated in order from 6 to 16 to naturally favor minimum UPS count
  // -------------------------------------------------------------------------
  for (let ups = 6; ups <= 16; ups++) {
    const totalSlit = jumboWidthMm * ups;
    const ps01Trim = motherDeckle - totalSlit;
    if (ps01Trim >= normalMinTrim && ps01Trim <= normalMaxTrim) {
      const sideAUps = Math.ceil(ups / 2);
      const sideBUps = Math.floor(ups / 2);
      const res: PS01FeasibilityEvaluation = {
        status: 'GREEN',
        is_feasible: true,
        ps01_deckle_mm: motherDeckle,
        jumbo_width_mm: jumboWidthMm,
        ps01_ups: ups,
        ps01_cut_combination: Array(ups).fill(jumboWidthMm),
        ps01_total_width_mm: totalSlit,
        ps01_trim_mm: ps01Trim,
        ps01_deckle_efficiency_percent: Number(((totalSlit / motherDeckle) * 100).toFixed(2)),
        ps01_duplex_balanced: true,
        side_a_ups: sideAUps,
        side_b_ups: sideBUps,
        relaxation_type: 'NONE',
        explanation: `${ups === 6 ? 'Preferred 6-UPS' : `${ups}-UPS`} jumbo manufacturing pattern on PS01 (${ups}×${jumboWidthMm}mm = ${totalSlit}mm, PS01 Trim: ${ps01Trim}mm within standard ${normalMinTrim}–${normalMaxTrim}mm)`,
      };
      singleFeasibilityCache.set(cacheKey, res);
      return res;
    }
  }

  // -------------------------------------------------------------------------
  // PRIORITY C: SS-side Trim Adjustment (Within 15–40 mm standard window)
  // Check 6–16 UPS with SS trim adjustment
  // -------------------------------------------------------------------------
  if (finishedWidths.length > 0) {
    const sumFinished = finishedWidths.reduce((a, b) => a + b, 0);

    for (let ups = 6; ups <= 16; ups++) {
      for (let testMslTrim = 15; testMslTrim <= 40; testMslTrim++) {
        if (testMslTrim === baseMslTrimMm) continue;
        const adjustedJumboWidth = sumFinished + testMslTrim;
        if (adjustedJumboWidth < 355 || adjustedJumboWidth > 1720) continue;

        const totalSlit = adjustedJumboWidth * ups;
        const ps01Trim = motherDeckle - totalSlit;
        if (ps01Trim >= normalMinTrim && ps01Trim <= normalMaxTrim) {
          const sideAUps = Math.ceil(ups / 2);
          const sideBUps = Math.floor(ups / 2);
          const res: PS01FeasibilityEvaluation = {
            status: 'YELLOW',
            is_feasible: true,
            ps01_deckle_mm: motherDeckle,
            jumbo_width_mm: adjustedJumboWidth,
            ps01_ups: ups,
            ps01_cut_combination: Array(ups).fill(adjustedJumboWidth),
            ps01_total_width_mm: totalSlit,
            ps01_trim_mm: ps01Trim,
            ps01_deckle_efficiency_percent: Number(((totalSlit / motherDeckle) * 100).toFixed(2)),
            ps01_duplex_balanced: true,
            side_a_ups: sideAUps,
            side_b_ups: sideBUps,
            relaxation_type: 'MSL_TRIM_ADJUSTED',
            relaxation_flag: `NON-STANDARD SS TRIM: Adjusted to ${testMslTrim} mm (within 20–40 mm window) to enable ${ups}-UPS on PS01`,
            explanation: `Feasible via SS trim adjustment to ${testMslTrim}mm -> ${ups}-UPS on PS01 (${ups}×${adjustedJumboWidth}mm = ${totalSlit}mm, PS01 Trim: ${ps01Trim}mm)`,
          };
          singleFeasibilityCache.set(cacheKey, res);
          return res;
        }
      }
    }
  }

  // -------------------------------------------------------------------------
  // PRIORITY D & E: Upstream PS01-side Trim Relaxation (Yellow 281 - 500 mm window)
  // Check 6–16 UPS under relaxed PS01 trim
  // -------------------------------------------------------------------------
  for (let ups = 6; ups <= 16; ups++) {
    const totalSlit = jumboWidthMm * ups;
    const ps01Trim = motherDeckle - totalSlit;
    if (ps01Trim > normalMaxTrim && ps01Trim <= 500) {
      const sideAUps = Math.ceil(ups / 2);
      const sideBUps = Math.floor(ups / 2);
      const res: PS01FeasibilityEvaluation = {
        status: 'YELLOW',
        is_feasible: true,
        ps01_deckle_mm: motherDeckle,
        jumbo_width_mm: jumboWidthMm,
        ps01_ups: ups,
        ps01_cut_combination: Array(ups).fill(jumboWidthMm),
        ps01_total_width_mm: totalSlit,
        ps01_trim_mm: ps01Trim,
        ps01_deckle_efficiency_percent: Number(((totalSlit / motherDeckle) * 100).toFixed(2)),
        ps01_duplex_balanced: true,
        side_a_ups: sideAUps,
        side_b_ups: sideBUps,
        relaxation_type: 'PS01_TRIM_RELAXED',
        relaxation_flag: `NON-STANDARD PS01 TRIM: Upstream trim relaxed to ${ps01Trim} mm (standard: ${normalMinTrim}–${normalMaxTrim} mm) for ${ups}-UPS`,
        explanation: `Feasible via Upstream PS01 Trim Relaxation (${ups}-UPS): ${ups}×${jumboWidthMm}mm = ${totalSlit}mm, PS01 Trim = ${ps01Trim}mm`,
      };
      singleFeasibilityCache.set(cacheKey, res);
      return res;
    }
  }

  // Otherwise completely infeasible
  const finalRedRes: PS01FeasibilityEvaluation = {
    status: 'RED',
    is_feasible: false,
    ps01_deckle_mm: motherDeckle,
    jumbo_width_mm: jumboWidthMm,
    ps01_ups: 0,
    ps01_cut_combination: [],
    ps01_total_width_mm: 0,
    ps01_trim_mm: 0,
    ps01_deckle_efficiency_percent: 0,
    ps01_duplex_balanced: false,
    side_a_ups: 0,
    side_b_ups: 0,
    relaxation_type: 'NONE',
    explanation: `Cannot manufacture jumbo width ${jumboWidthMm} mm on PS01: 6–16 UPS are infeasible, and 1–5 UPS are strictly forbidden for SS upstream jumbo roll manufacturing (10,400 mm master deckle)`,
  };
  singleFeasibilityCache.set(cacheKey, finalRedRes);
  return finalRedRes;
}

/**
 * Generate a separate, authoritative PS01 SlitterPlan for an INDIVIDUAL Jumbo Roll Plan or multi-width jumbo combination.
 * STRICT REQUIREMENT: Each Jumbo Plan has its own isolated Factory Sheet with NO cross-plan data mixing.
 */
export function generatePS01PlanForJumboCombination(
  jumboWidths: number[],
  planIndex: number,
  film: string,
  lengthM: number,
  thickness: number = 18,
  associatedReqs: SSJumboRequirement[] = [],
  createdBy: string = 'M.USMAN (Planner)',
  repetitions: number = 1,
  motherDeckleMm?: number
): SlitterPlan {
  const motherDeckle = [10400, 10330, 8700, 8630].includes(Number(motherDeckleMm))
    ? Number(motherDeckleMm)
    : (DEFAULT_PLANNING_RULES.deckle_width_mm || 10400);
  const ps01Ups = jumboWidths.length;
  const sideAUps = Math.ceil(ps01Ups / 2);
  const sideBUps = Math.floor(ps01Ups / 2);
  const totalSlitWidth = jumboWidths.reduce((a, b) => a + b, 0);
  const trimMm = motherDeckle - totalSlitWidth;
  const _d = resolveFilmDensity(typeof film !== 'undefined' ? film : '');
  const density = (_d != null && _d > 0) ? _d : (() => { throw new Error('Density missing in Film Specs Master DB'); })();
  const dateStr = new Date().toISOString();
  const displayDate = new Date().toLocaleDateString('en-GB');

  // Authoritative weight calculation per item
  const items: PlanItem[] = [];
  let currentSideAArm = 1;
  let currentSideBArm = 9;
  let totalPlannedQuantityKg = 0;

  const planId = `ps01-plan-ss-${Date.now()}-${planIndex + 1}`;
  const widthSummary = jumboWidths.length <= 2 
    ? jumboWidths.join('+') + 'MM' 
    : `${jumboWidths[0]}+${jumboWidths[1]}+${jumboWidths[2]}${jumboWidths[3] ? '+' + jumboWidths[3] : ''}MM`;
  const planNumber = `PS01-SS-JP${planIndex + 1}-${film}-${widthSummary}`;
  const segmentId = `seg-ps01-ss-${planIndex + 1}-1`;

  const uniqueWidths = Array.from(new Set(jumboWidths));

  for (let i = 0; i < ps01Ups; i++) {
    const width = jumboWidths[i];
    const isSideA = i % 2 === 0 ? (currentSideAArm <= sideAUps) : (currentSideBArm > 8 + sideBUps);
    const station: 'SIDE_A' | 'SIDE_B' = isSideA ? 'SIDE_A' : 'SIDE_B';
    const physicalArm = station === 'SIDE_A' ? currentSideAArm++ : currentSideBArm++;
    const posIndex = i + 1;

    const singleReelWeightKg = Number(((width * lengthM * thickness * density) / 1000000).toFixed(2));
    const itemTotalWeightKg = Number((singleReelWeightKg * repetitions).toFixed(2));
    totalPlannedQuantityKg += itemTotalWeightKg;

    const matchedReq = associatedReqs[i] || associatedReqs.find(r => r.required_jumbo_width_mm === width) || associatedReqs[0];
    const formatWidthsMultiplier = (widths: number[]): string => {
      if (!widths || widths.length === 0) return '';
      const counts = new Map<number, number>();
      for (const w of widths) {
        counts.set(w, (counts.get(w) || 0) + 1);
      }
      return Array.from(counts.entries())
        .map(([w, count]) => (count > 1 ? `${w}*${count}` : `${w}`))
        .join(' + ');
    };
    const customerLabel = matchedReq 
      ? `SS ${matchedReq.ups}-UPS: ${formatWidthsMultiplier(matchedReq.finished_widths_covered || [])}`
      : `${width}mm JUMBO`;

    const uniqueIndex = uniqueWidths.indexOf(width);
    const sizeItemNumber = (uniqueIndex + 1) * 10;

    items.push({
      id: `item-${planId}-${posIndex}`,
      plan_id: planId,
      segment_id: segmentId,
      position: physicalArm,
      positions: [physicalArm],
      position_label: `Pos ${posIndex} (Arm ${physicalArm})`,
      station: station,
      sales_order: `JR-${film}-${width}`,
      item_number: sizeItemNumber,
      customer: customerLabel,
      film: film,
      width_mm: width,
      length_m: lengthM,
      core: 6,
      treatment_side: 'OS',
      reels: repetitions,
      ups: 1,
      initial_ups: 1,
      deckle_mm: width,
      weight_per_pack_kg: singleReelWeightKg,
      total_weight_kg: itemTotalWeightKg,
      is_closed: true,
      parent_deckle_id: matchedReq?.ps01_parent_deckle_id,
      source_requirement_id: matchedReq?.id,
    });
  }

  totalPlannedQuantityKg = Number(totalPlannedQuantityKg.toFixed(2));
  const singleMillRollWeightKg = Number(((motherDeckle * lengthM * thickness * density) / 1000000).toFixed(2));
  const singleTrimWeightKg = Number(((trimMm * lengthM * thickness * density) / 1000000).toFixed(2));
  const millRollWeightKg = Number((singleMillRollWeightKg * repetitions).toFixed(2));
  const trimWeightKg = Number((singleTrimWeightKg * repetitions).toFixed(2));
  const wastePercent = Number(((trimMm / motherDeckle) * 100).toFixed(2));

  const segment: PlanSegment = {
    id: segmentId,
    plan_id: planId,
    segment_number: 1,
    name: `SS Jumbo Slit Layout (${ps01Ups}-UPS on 10,400mm Mother Deckle)`,
    start_pack: 1,
    end_pack: repetitions,
    repetitions: repetitions,
    total_slit_width_mm: totalSlitWidth,
    trim_mm: trimMm,
    ups: ps01Ups,
    items: items,
  };

  const isRelaxed = trimMm > 280 && trimMm <= 500;

  return {
    id: planId,
    planning_run_id: `run-jumbo-ss-${film}`,
    plan_number: planNumber,
    machine_id: 'PS01',
    machine_name: 'PRIMARY SLITTER 1 (PS01)',
    film: film,
    thickness_micron: thickness,
    density: density,
    deckle_mm: motherDeckle,
    total_slit_width_mm: totalSlitWidth,
    trim_mm: trimMm,
    allowed_trim_mm: 280,
    remaining_web_mm: 0,
    ups: ps01Ups,
    max_ups_capacity: 16,
    repetitions: repetitions,
    length_m: lengthM,
    planned_mr_length_m: lengthM,
    mill_roll_weight_kg: millRollWeightKg,
    trim_weight_kg: trimWeightKg,
    waste_percent: wastePercent,
    planned_quantity_kg: totalPlannedQuantityKg,
    order_weight_kg: totalPlannedQuantityKg,
    total_reels: ps01Ups * repetitions,
    weight_per_pack_total_kg: Number((totalPlannedQuantityKg / repetitions).toFixed(2)),
    rejection_material: `R-${film}`,
    trim_rule_mode: isRelaxed ? 'RELAXED_50MM' : 'NORMAL',
    min_trim_mm_used: isRelaxed ? 281 : 150,
    max_trim_mm_used: isRelaxed ? 500 : 280,
    duplex_layout: {
      side_a_ups: sideAUps,
      side_b_ups: sideBUps,
      is_dual_core: false,
      is_dual_length: false,
      balance_delta: Math.abs(sideAUps - sideBUps),
    },
    doc_ref: 'APS/QR/PL/01',
    rev_no: 0,
    issue_date: displayDate,
    items: items,
    changes: [],
    segments: [segment],
    status: 'APPROVED',
    approved_by: createdBy,
    approved_at: dateStr,
    created_at: dateStr,
  };
}

export interface SSWidthWiseReconciliationResult {
  is_valid: boolean;
  errors: string[];
  widthDetails: {
    width_mm: number;
    manufactured_count: number;
    consumed_count: number;
    difference: number;
    film?: string;
    length_m?: number;
  }[];
}

/**
 * Validates width-wise quantity reconciliation between manufactured PS01 jumbo rolls and downstream SS consumption.
 * Enforces:
 * - For EACH jumbo width W independently: Manufactured(W) === Consumed(W).
 * - Zero unallocated manufactured rolls (manufactured > consumed is REJECTED).
 * - Zero downstream consumption of unmanufactured rolls (consumed > manufactured is REJECTED).
 * - Physical attribute checks where data exists (film, length, parent deckle ID, source requirement ID).
 */
export function validateSSWidthWiseJumboReconciliation(
  manufacturedJumbos:
    | Array<{
        width_mm?: number;
        count?: number;
        length_m?: number;
        film?: string;
        parent_deckle_id?: string;
        source_requirement_id?: string;
      }>
    | number[]
    | SlitterPlan[],
  consumedJumbos:
    | Array<{
        width_mm?: number;
        required_jumbo_width_mm?: number;
        count?: number;
        required_rolls_count?: number;
        length_m?: number;
        required_jumbo_length_m?: number;
        film?: string;
        ps01_parent_deckle_id?: string;
        id?: string;
        source_requirement_id?: string;
      }>
    | any[]
): SSWidthWiseReconciliationResult {
  const mfgCounts = new Map<number, number>();
  const consumedCounts = new Map<number, number>();
  const mfgItemsByWidth = new Map<number, any[]>();
  const consumedItemsByWidth = new Map<number, any[]>();

  // Process manufactured
  if (Array.isArray(manufacturedJumbos)) {
    for (const item of manufacturedJumbos) {
      if (typeof item === 'number') {
        mfgCounts.set(item, (mfgCounts.get(item) || 0) + 1);
        if (!mfgItemsByWidth.has(item)) mfgItemsByWidth.set(item, []);
        mfgItemsByWidth.get(item)!.push({ width_mm: item, count: 1 });
      } else if (item && 'items' in item && Array.isArray((item as SlitterPlan).items)) {
        const plan = item as SlitterPlan;
        const sets = plan.repetitions || (plan as any).total_sets || 1;
        for (const slitItem of plan.items) {
          const w = slitItem.width_mm;
          const c = sets;
          mfgCounts.set(w, (mfgCounts.get(w) || 0) + c);
          if (!mfgItemsByWidth.has(w)) mfgItemsByWidth.set(w, []);
          mfgItemsByWidth.get(w)!.push({
            width_mm: w,
            count: c,
            length_m: slitItem.length_m || plan.length_m,
            film: slitItem.film || plan.film,
            parent_deckle_id: slitItem.parent_deckle_id,
            source_requirement_id: slitItem.source_requirement_id,
          });
        }
      } else if (item && typeof item === 'object') {
        const w = (item as any).width_mm;
        const c = (item as any).count ?? 1;
        if (typeof w === 'number') {
          mfgCounts.set(w, (mfgCounts.get(w) || 0) + c);
          if (!mfgItemsByWidth.has(w)) mfgItemsByWidth.set(w, []);
          mfgItemsByWidth.get(w)!.push(item);
        }
      }
    }
  }

  // Process consumed
  if (Array.isArray(consumedJumbos)) {
    for (const item of consumedJumbos) {
      if (item && typeof item === 'object') {
        const w = (item as any).required_jumbo_width_mm ?? (item as any).jumbo_width_mm ?? (item as any).width_mm;
        const c = (item as any).required_rolls_count ?? (item as any).jumbo_rolls_count ?? (item as any).repeat_count ?? (item as any).count ?? 1;
        if (typeof w === 'number') {
          consumedCounts.set(w, (consumedCounts.get(w) || 0) + c);
          if (!consumedItemsByWidth.has(w)) consumedItemsByWidth.set(w, []);
          consumedItemsByWidth.get(w)!.push(item);
        }
      }
    }
  }

  const allWidths = Array.from(new Set([...mfgCounts.keys(), ...consumedCounts.keys()])).sort((a, b) => a - b);
  const errors: string[] = [];

  const widthDetails = allWidths.map(w => {
    const mfg = mfgCounts.get(w) || 0;
    const con = consumedCounts.get(w) || 0;
    const diff = mfg - con;

    if (diff !== 0) {
      if (diff > 0) {
        errors.push(`Width ${w}mm: Manufactured ${mfg} rolls, but SS only consumes ${con} rolls (${diff} unallocated rolls).`);
      } else {
        errors.push(`Width ${w}mm: SS consumes ${con} rolls, but PS01 only manufactures ${mfg} rolls (missing ${-diff} rolls).`);
      }
    }

    // Physical identity checks where data exists:
    const mfgList = mfgItemsByWidth.get(w) || [];
    const conList = consumedItemsByWidth.get(w) || [];

    // 1. Parent deckle ID provenance check:
    // Rolls manufactured for parent run P can only supply SS requirements for parent run P (zero cross-parent cannibalization)
    const mfgParentCounts = new Map<string, number>();
    const conParentCounts = new Map<string, number>();
    let mfgUnparented = 0;
    let conUnparented = 0;

    for (const m of mfgList) {
      const pid = m.parent_deckle_id;
      const count = m.count ?? 1;
      if (pid) {
        mfgParentCounts.set(pid, (mfgParentCounts.get(pid) || 0) + count);
      } else {
        mfgUnparented += count;
      }
    }

    for (const c of conList) {
      const pid = c.ps01_parent_deckle_id || c.parent_deckle_id;
      const count = c.required_rolls_count ?? c.jumbo_rolls_count ?? c.repeat_count ?? c.count ?? 1;
      if (pid) {
        conParentCounts.set(pid, (conParentCounts.get(pid) || 0) + count);
      } else {
        conUnparented += count;
      }
    }

    if (mfgParentCounts.size > 0 && conParentCounts.size > 0) {
      const allParents = new Set([...mfgParentCounts.keys(), ...conParentCounts.keys()]);
      for (const pid of allParents) {
        const mfgCountForParent = mfgParentCounts.get(pid) || 0;
        const conCountForParent = conParentCounts.get(pid) || 0;
        if (mfgCountForParent !== conCountForParent) {
          if (mfgCountForParent > conCountForParent) {
            errors.push(
              `Width ${w}mm: Physical Deckle Provenance Violation - PS01 run '${pid}' manufactured ${mfgCountForParent} rolls, but SS run '${pid}' only consumes ${conCountForParent} rolls (${mfgCountForParent - conCountForParent} unallocated rolls).`
            );
          } else {
            errors.push(
              `Width ${w}mm: Physical Deckle Provenance Violation - SS run '${pid}' requires ${conCountForParent} rolls, but PS01 run '${pid}' only manufactured ${mfgCountForParent} rolls (missing ${conCountForParent - mfgCountForParent} rolls).`
            );
          }
        }
      }

      if (mfgUnparented !== conUnparented) {
        errors.push(
          `Width ${w}mm: Physical Deckle Provenance Violation - Unparented rolls mismatch: ${mfgUnparented} manufactured vs ${conUnparented} consumed.`
        );
      }
    }

    // 2. Film consistency (within parent run if present)
    for (const c of conList) {
      const cParent = c.ps01_parent_deckle_id || c.parent_deckle_id;
      const cFilm = c.film;
      if (!cFilm) continue;
      const candidates = mfgList.filter(m => (cParent || m.parent_deckle_id) ? m.parent_deckle_id === cParent : true);
      for (const m of candidates) {
        if (m.film && m.film !== cFilm) {
          errors.push(`Width ${w}mm: Physical Film Mismatch - PS01 manufactured '${m.film}' but SS consumes '${cFilm}'.`);
        }
      }
    }

    // 3. Length consistency (within parent run if present)
    for (const c of conList) {
      const cParent = c.ps01_parent_deckle_id || c.parent_deckle_id;
      const reqLen = c.required_jumbo_length_m ?? c.length_m ?? c.jumbo_length_m;
      if (!reqLen) continue;
      const candidates = mfgList.filter(m => (cParent || m.parent_deckle_id) ? m.parent_deckle_id === cParent : true);
      for (const m of candidates) {
        if (m.length_m && m.length_m < reqLen) {
          errors.push(`Width ${w}mm: Physical Length Deficit - PS01 manufactured ${m.length_m}m but SS requires ${reqLen}m.`);
        }
      }
    }

    // 4. Source requirement ID check if single requirement on both sides
    if (mfgList.length === 1 && conList.length === 1) {
      const mfgReqId = mfgList[0].source_requirement_id;
      const conReqId = conList[0].id ?? conList[0].source_requirement_id;
      if (mfgReqId && conReqId && mfgReqId !== conReqId) {
        errors.push(`Width ${w}mm: Source Requirement Mismatch - Manufactured for '${mfgReqId}' but assigned to '${conReqId}'.`);
      }
    }

    return {
      width_mm: w,
      manufactured_count: mfg,
      consumed_count: con,
      difference: diff,
      film: conList[0]?.film || mfgList[0]?.film,
      length_m: conList[0]?.required_jumbo_length_m || mfgList[0]?.length_m,
    };
  });

  return {
    is_valid: errors.length === 0,
    errors,
    widthDetails,
  };
}

export const validateWidthWiseJumboReconciliation = validateSSWidthWiseJumboReconciliation;
export type WidthWiseReconciliationResult = SSWidthWiseReconciliationResult;

/**
 * Generate a separate, authoritative PS01 SlitterPlan for a complete Mother Roll Deckle Run Group.
 */
export function generatePS01PlanForDeckleGroup(
  reqs: SSJumboRequirement[],
  runIndex: number,
  film: string,
  createdBy: string = 'M.USMAN (Planner)',
  motherDeckleMm?: number
): SlitterPlan {
  if (!reqs || reqs.length === 0) {
    throw new Error('No requirements provided for mother run group');
  }

  const primaryReq = reqs[0];
  const feasibility = primaryReq.ps01_feasibility;
  let cutCombination = feasibility?.ps01_cut_combination && feasibility.ps01_cut_combination.length > 0
    ? [...feasibility.ps01_cut_combination]
    : Array(feasibility?.ps01_ups || (primaryReq.required_jumbo_width_mm <= 2600 ? 4 : 3)).fill(primaryReq.required_jumbo_width_mm);

  // If all requirements in this deckle group have the same width W, enforce cutCombination is pure W:
  const allSameWidth = reqs.every(r => r.required_jumbo_width_mm === primaryReq.required_jumbo_width_mm);
  const isPureDeckle = cutCombination.every(w => w === cutCombination[0]);

  if (allSameWidth && (isPureDeckle || cutCombination.length === 3 || cutCombination.length === 4 || cutCombination.length >= 6)) {
    cutCombination = Array(cutCombination.length).fill(primaryReq.required_jumbo_width_mm);
  }

  // Count how many times each jumbo width appears in this mother deckle pattern
  const patternWidthCounts = new Map<number, number>();
  cutCombination.forEach(w => patternWidthCounts.set(w, (patternWidthCounts.get(w) || 0) + 1));

  // Calculate repetitions (number of PS01 Mother Roll packs/sets needed)
  // For each unique width W in cutCombination, sets needed = ceil(total_demand_for_W / slots_of_W_in_pattern)
  let setsNeeded = 1;
  for (const [w, slotsInPattern] of patternWidthCounts.entries()) {
    const totalRollsNeededForWidth = reqs
      .filter(r => r.required_jumbo_width_mm === w)
      .reduce((sum, r) => sum + (r.required_rolls_count || 1), 0);
    const setsForWidth = Math.max(1, Math.ceil(totalRollsNeededForWidth / slotsInPattern));
    if (setsForWidth > setsNeeded) {
      setsNeeded = setsForWidth;
    }
  }

  // Map each cut position to the specific SS requirement that utilizes this jumbo width
  const associatedReqs: SSJumboRequirement[] = [];
  const assignedCountsPerReq = new Map<string, number>();

  for (let i = 0; i < cutCombination.length; i++) {
    const cutWidth = cutCombination[i];
    const matchingReqs = reqs.filter(r => r.required_jumbo_width_mm === cutWidth);
    let assignedReq = matchingReqs[0] || primaryReq;

    if (matchingReqs.length > 1) {
      // Pick the requirement that still needs more slots in the pattern (unmet slot quota)
      matchingReqs.sort((a, b) => {
        const quotaA = Math.ceil((a.required_rolls_count || 1) / setsNeeded);
        const quotaB = Math.ceil((b.required_rolls_count || 1) / setsNeeded);
        const assignedA = assignedCountsPerReq.get(a.id) || 0;
        const assignedB = assignedCountsPerReq.get(b.id) || 0;
        return (quotaB - assignedB) - (quotaA - assignedA);
      });
      assignedReq = matchingReqs[0];
    }

    associatedReqs.push(assignedReq);
    assignedCountsPerReq.set(assignedReq.id, (assignedCountsPerReq.get(assignedReq.id) || 0) + 1);
  }

  const lengthM = Math.max(...reqs.map(r => r.required_jumbo_length_m || 20000));
  const thickness = primaryReq.thickness_micron || 18;

  const resolvedDeckle = [10400, 10330, 8700, 8630].includes(Number(motherDeckleMm))
    ? Number(motherDeckleMm)
    : (primaryReq.ps01_feasibility?.ps01_deckle_mm
        || DEFAULT_PLANNING_RULES.deckle_width_mm
        || 10400);
  const plan = generatePS01PlanForJumboCombination(
    cutCombination,
    runIndex - 1,
    film,
    lengthM,
    thickness,
    associatedReqs,
    createdBy,
    setsNeeded,
    resolvedDeckle
  );

  // Hard width-wise quantity reconciliation guard
  const mfgRolls: { width_mm: number; count: number; film?: string; length_m?: number; parent_deckle_id?: string }[] = [];
  for (const [w, countInPattern] of patternWidthCounts.entries()) {
    mfgRolls.push({
      width_mm: w,
      count: countInPattern * setsNeeded,
      film,
      length_m: lengthM,
      parent_deckle_id: primaryReq.ps01_parent_deckle_id,
    });
  }
  const reconciliation = validateSSWidthWiseJumboReconciliation(mfgRolls, reqs);
  if (!reconciliation.is_valid) {
    // Surgical: allow PS01 ceiling surplus (e.g. 20 SS rolls → 4×6=24 PS01 slots).
    // Only hard-fail on shortage (SS needs more than PS01 manufactures).
    const onlySurplus = reconciliation.errors.every(
      e => typeof e === 'string' && (e.includes('unallocated rolls') || e.includes('only consumes'))
    );
    const isFixed1705 =
      reqs.every(r => r.required_jumbo_width_mm === 1705) &&
      (String(film || '').toUpperCase() === 'MATTPL12' ||
        String(film || '').toUpperCase() === 'TNBPL10' ||
        reqs.some(r => {
          const f = String(r.film || '').toUpperCase();
          return f === 'MATTPL12' || f === 'TNBPL10';
        }));

    if (!(onlySurplus || isFixed1705)) {
      throw new Error(
        `PS01 Width-Wise Quantity Reconciliation Guard Violation: SS Deckle run #${runIndex} (${film}) reconciliation failed:\n${reconciliation.errors.join('\n')}`
      );
    }
    // Surplus / fixed-1705: proceed — factory sheet still valid
  }

  return plan;
}

/**
 * Generate a separate, authoritative PS01 SlitterPlan for an INDIVIDUAL Jumbo Roll Plan.
 */
export function generatePS01PlanForSingleJumbo(
  req: SSJumboRequirement,
  planIndex: number,
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): SlitterPlan {
  const feasibilityCuts = req.ps01_feasibility?.ps01_cut_combination;
  let widths = feasibilityCuts && feasibilityCuts.length > 0
    ? [...feasibilityCuts]
    : Array(req.ps01_feasibility?.ps01_ups || (req.required_jumbo_width_mm <= 2600 ? 4 : 3)).fill(req.required_jumbo_width_mm);

  // If pure pattern or single jumbo requirement representing pure cuts:
  const isPurePattern = widths.every(w => w === widths[0]) || widths.every(w => Math.abs(w - req.required_jumbo_width_mm) <= 30);
  if (isPurePattern) {
    widths = Array(widths.length).fill(req.required_jumbo_width_mm);
  }

  const matchingWidthCount = widths.filter(w => w === req.required_jumbo_width_mm).length;
  const upsInPattern = isPurePattern ? widths.length : Math.max(1, matchingWidthCount);
  const setsNeeded = Math.max(1, Math.ceil((req.required_rolls_count || 1) / upsInPattern));

  const plan = generatePS01PlanForJumboCombination(
    widths,
    planIndex,
    film,
    req.required_jumbo_length_m,
    req.thickness_micron || 18,
    Array(widths.length).fill(req),
    createdBy,
    setsNeeded,
    req.ps01_feasibility?.ps01_deckle_mm
  );

  // Hard width-wise quantity reconciliation guard
  const patternWidthCounts = new Map<number, number>();
  widths.forEach(w => patternWidthCounts.set(w, (patternWidthCounts.get(w) || 0) + 1));
  const mfgRolls: { width_mm: number; count: number; film?: string; length_m?: number; parent_deckle_id?: string }[] = [];
  for (const [w, countInPattern] of patternWidthCounts.entries()) {
    mfgRolls.push({
      width_mm: w,
      count: countInPattern * setsNeeded,
      film,
      length_m: req.required_jumbo_length_m,
      parent_deckle_id: req.ps01_parent_deckle_id,
    });
  }
  const reconciliation = validateSSWidthWiseJumboReconciliation(mfgRolls, [req]);
  if (!reconciliation.is_valid) {
    // Surgical: allow ceiling surplus (ceil to full PS01 UPS) — only hard-fail on shortage
    const onlySurplus = reconciliation.errors.every(
      e => typeof e === 'string' && (e.includes('unallocated rolls') || e.includes('only consumes'))
    );
    const filmKey = String(film || req.film || '').toUpperCase();
    const isFixed1705 =
      req.required_jumbo_width_mm === 1705 &&
      (filmKey === 'MATTPL12' || filmKey === 'TNBPL10');

    if (!(onlySurplus || isFixed1705)) {
      throw new Error(
        `PS01 Width-Wise Quantity Reconciliation Guard Violation: SS Single-jumbo plan #${planIndex + 1} (${film}) reconciliation failed:\n${reconciliation.errors.join('\n')}`
      );
    }
  }

  return plan;
}

/**
 * Generate a customer-standard SlitterPlan for a Secondary Slitter (SS) Plan.
 */
export function generateSSSlitterPlan(
  req: SSJumboRequirement,
  planIndex: number,
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): SlitterPlan {
  /**
   * SS Factory Sheet — source of truth = req.orders_covered (optimizer output).
   * Optimizer already enforces demand × 1.10. This function must NOT re-inflate
   * weights by multiplying full-run packs × every pattern width.
   *
   * Physical header (REPETITIONS / mill roll) uses max reels among covered orders
   * (how many packs the run actually needed for the bottleneck width).
   */
  const mountJumboWidth = req.required_jumbo_width_mm;
  const finishedCuts = (req.finished_widths_covered || []).slice();
  const mslUps = finishedCuts.length || req.ups || 1;
  const totalSlitWidth = finishedCuts.reduce((a, b) => a + b, 0);
  const trimMm =
    req.expected_trim_mm !== undefined
      ? req.expected_trim_mm
      : Math.max(0, mountJumboWidth - totalSlitWidth);
  const densityFromMaster = resolveFilmDensity(film);
  if (densityFromMaster == null || !(densityFromMaster > 0)) {
    throw new Error(
      `Density not saved in Film Specs Master Database for: ${film}. Open Master Backlog → Film Specs Master DB and add density before SS planning.`
    );
  }
  const density = densityFromMaster;
  const jumboLengthM = req.required_jumbo_length_m || 20000;
  const thickness = req.thickness_micron || 18;
  const jumboRollsCount = Math.max(1, req.required_rolls_count || 1);
  const dateStr = new Date().toISOString();
  const displayDate = new Date().toLocaleDateString('en-GB');

  const ordersCovered = req.orders_covered || [];
  const coveredLengths = ordersCovered.map(o => o.length_m).filter(Boolean) as number[];
  const packLengthM =
    coveredLengths.length > 0
      ? Math.max(...coveredLengths)
      : Math.round(jumboLengthM / Math.max(1, req.package_multiple || 1));
  const setsPerJumbo = Math.max(1, Math.round(jumboLengthM / Math.max(1, packLengthM)));

  // totalPacks computed after pattern UPS known (reels ÷ simultaneous UPS per width)
  let totalPacks = Math.max(1, jumboRollsCount * setsPerJumbo);

  const planId = `ss-slitter-plan-${req.id || planIndex + 1}`;
  const widthSummary =
    finishedCuts.length <= 3
      ? finishedCuts.join('+') + 'MM'
      : `${finishedCuts.slice(0, 3).join('+')}+${finishedCuts.length - 3}MORE`;
  const planNumber = `SS-P${planIndex + 1}-${film}-${mountJumboWidth}MM-(${widthSummary})`;
  const segmentId = `seg-ss-${planIndex + 1}-1`;

  const items: PlanItem[] = [];
  let totalPlannedQuantityKg = 0;

  /**
   * PS-style sheet layout for SS:
   * - Only widths that genuinely exist on this plan's knife pattern (finished_widths_covered)
   * - First customer/SO/item on a width = active row with UPS = count of that width in pattern
   * - Same width, later customer/SO/item = sequential fill under that line: UPS "-", no FUTURE SHIFT
   * - FUTURE SHIFT only if a row introduces a width change (not used for pure sequential same-size)
   */
  const patternWidths = finishedCuts.filter(w => Number(w) > 0);
  const patternSet = new Set(patternWidths.map(w => Number(w)));
  const upsByWidth = new Map<number, number>();
  patternWidths.forEach(w => {
    const n = Number(w);
    upsByWidth.set(n, (upsByWidth.get(n) || 0) + 1);
  });

  // Keep only orders whose width is on the physical pattern
  const patternOrders = ordersCovered.filter(oc => patternSet.has(Number(oc.width_mm)));

  // Stable pattern order of unique widths (first appearance in knife pattern)
  const uniquePatternOrder: number[] = [];
  for (const w of patternWidths) {
    const n = Number(w);
    if (!uniquePatternOrder.includes(n)) uniquePatternOrder.push(n);
  }

  let rowIdx = 0;
  let armA = 1;
  let armB = 9;

  for (const width of uniquePatternOrder) {
    const widthUps = upsByWidth.get(width) || 1;
    const group = patternOrders
      .filter(oc => Number(oc.width_mm) === width)
      .sort((a, b) => {
        // Larger allocation first (fills initial packs)
        const ra = Number(a.required_reels || 0);
        const rb = Number(b.required_reels || 0);
        if (rb !== ra) return rb - ra;
        return String(a.sales_order || '').localeCompare(String(b.sales_order || ''));
      });

    if (group.length === 0) continue;

    // Position arms for this width (one arm per simultaneous UPS of this size)
    const positions: number[] = [];
    for (let u = 0; u < widthUps; u++) {
      const isSideA = positions.length % 2 === 0;
      positions.push(isSideA ? armA++ : armB++);
    }

    let packCursor = 1; // next pack index for sequential same-size fills

    group.forEach((oc, gIdx) => {
      const lengthM = oc.length_m || packLengthM;
      const reels = Math.max(0, Math.round(Number(oc.required_reels || 0)));
      const weightKg = Number(Number(oc.weight_kg || 0).toFixed(2));
      if (reels <= 0 && weightKg <= 0.01) return; // nothing genuinely running

      const singleReelWeightKg =
        reels > 0
          ? Number((weightKg / reels).toFixed(2))
          : Number(((width * lengthM * thickness * density) / 1000000).toFixed(2));
      const reelsPerPack = Math.max(1, widthUps); // each pack yields widthUps reels of this size
      const packsForOrder = Math.max(1, Math.ceil(reels / reelsPerPack));
      const isActive = gIdx === 0; // first order on this size owns UPS
      const startPack = packCursor;
      packCursor += packsForOrder;

      totalPlannedQuantityKg += weightKg;
      rowIdx++;

      items.push({
        id: `item-${planId}-${rowIdx}`,
        plan_id: planId,
        segment_id: segmentId,
        position: positions[0] || rowIdx,
        positions: positions.slice(),
        position_label: `Pos ${positions.join(',')} (Arm ${positions.join('/')})`,
        station: (positions[0] || 1) < 9 ? 'SIDE_A' : 'SIDE_B',
        sales_order: oc.sales_order ? `SO#${oc.sales_order}` : `SO-SS-${rowIdx}`,
        item_number: oc.item_number || rowIdx * 10,
        customer: oc.customer || 'SECONDARY SLITTER',
        film,
        width_mm: width,
        length_m: lengthM,
        core: 6,
        treatment_side: 'OS',
        reels,
        // Active size row: real UPS. Sequential same-size: 0 → sheet shows "-"
        ups: isActive ? widthUps : 0,
        initial_ups: isActive ? widthUps : 0,
        active_packs: packsForOrder,
        start_pack: startPack,
        deckle_mm: isActive ? width * widthUps : 0,
        weight_per_pack_kg: isActive
          ? Number((singleReelWeightKg * widthUps).toFixed(2))
          : 0,
        total_weight_kg: weightKg,
        is_closed: true,
        // Same size sequential ≠ size change → never FUTURE SHIFT here
        is_future_replacement: false,
      } as PlanItem);
    });
  }

  // Legacy fallback only if pattern exists but no order lines matched
  if (items.length === 0 && patternWidths.length > 0) {
    patternWidths.forEach((w, i) => {
      const lengthM = packLengthM;
      const rpp = 1;
      const reels = totalPacks * rpp;
      const singleReelWeightKg = Number(((w * lengthM * thickness * density) / 1000000).toFixed(2));
      const weightKg = Number((singleReelWeightKg * reels).toFixed(2));
      const isSideA = i % 2 === 0;
      const station: 'SIDE_A' | 'SIDE_B' = isSideA ? 'SIDE_A' : 'SIDE_B';
      const physicalArm = isSideA ? armA++ : armB++;
      totalPlannedQuantityKg += weightKg;
      items.push({
        id: `item-${planId}-fb-${i + 1}`,
        plan_id: planId,
        segment_id: segmentId,
        position: physicalArm,
        positions: [physicalArm],
        position_label: `Pos ${i + 1} (Arm ${physicalArm})`,
        station,
        sales_order: `SO-SS-${i + 1}`,
        item_number: (i + 1) * 10,
        customer: 'SECONDARY SLITTER',
        film,
        width_mm: w,
        length_m: lengthM,
        core: 6,
        treatment_side: 'OS',
        reels,
        ups: 1,
        initial_ups: 1,
        deckle_mm: w,
        weight_per_pack_kg: Number((singleReelWeightKg * rpp).toFixed(2)),
        total_weight_kg: weightKg,
        is_closed: true,
        is_future_replacement: false,
      } as PlanItem);
    });
  }

  totalPlannedQuantityKg = Number(totalPlannedQuantityKg.toFixed(2));

  // REPETITIONS (packs) = max over pattern widths of ceil(total_reels_of_width / simultaneous_UPS)
  // Example: 4×342 mm pattern, 3120 reels of 342 → ceil(3120/4) = 780 packs (NOT 1260 reels).
  let packsFromPattern = 0;
  for (const [w, ups] of upsByWidth.entries()) {
    const reelsOfW = items
      .filter(it => Number(it.width_mm) === Number(w))
      .reduce((s, it) => s + (Number(it.reels) || 0), 0);
    if (reelsOfW <= 0) continue;
    const packsW = Math.ceil(reelsOfW / Math.max(1, ups));
    if (packsW > packsFromPattern) packsFromPattern = packsW;
  }
  // Fallback: sum sequential start_pack spans from items
  if (packsFromPattern <= 0 && items.length > 0) {
    let maxEnd = 0;
    for (const it of items) {
      const start = Number((it as any).start_pack) || 1;
      const active = Number((it as any).active_packs) || 0;
      const end = active > 0 ? start + active - 1 : start;
      if (end > maxEnd) maxEnd = end;
    }
    packsFromPattern = maxEnd;
  }
  const headerPacks = Math.max(1, packsFromPattern || totalPacks);
  totalPacks = headerPacks;

  const utilizedWebMm = Math.max(0, mountJumboWidth - trimMm);
  const singlePackMillRollWeightKg = Number(
    ((mountJumboWidth * packLengthM * thickness * density) / 1000000).toFixed(2)
  );
  const singlePackTrimWeightKg = Number(
    ((trimMm * packLengthM * thickness * density) / 1000000).toFixed(2)
  );
  const millRollWeightKg = Number((singlePackMillRollWeightKg * headerPacks).toFixed(2));
  const trimWeightKg = Number((singlePackTrimWeightKg * headerPacks).toFixed(2));
  const wastePercent = Number(((trimMm / Math.max(1, mountJumboWidth)) * 100).toFixed(2));
  const totalReelsCount = items.reduce((sum, item) => sum + item.reels, 0);

  const segment: PlanSegment = {
    id: segmentId,
    plan_id: planId,
    segment_number: 1,
    name: `SS Finished Slit Pattern (${mslUps}-UPS on ${mountJumboWidth}mm Jumbo Mount)`,
    start_pack: 1,
    end_pack: headerPacks,
    repetitions: headerPacks,
    length_m: packLengthM,
    items: items,
  };

  const actualSideAUps = items.filter(i => i.station === 'SIDE_A').length;
  const actualSideBUps = items.filter(i => i.station === 'SIDE_B').length;

  return {
    id: planId,
    plan_number: planNumber,
    machine_id: 'SS',
    machine_name: 'SECONDARY SLITTER (SS)',
    film: film,
    thickness_micron: thickness,
    density: density,
    core: 6,
    deckle_mm: mountJumboWidth,
    trim_mm: trimMm,
    ups: mslUps,
    status: 'APPROVED' as any,
    created_by: createdBy,
    created_at: dateStr,
    approved_by: createdBy,
    approved_at: dateStr,
    repetitions: headerPacks,
    length_m: packLengthM,
    planned_mr_length_m: packLengthM * headerPacks,
    mill_roll_weight_kg: millRollWeightKg,
    trim_weight_kg: trimWeightKg,
    waste_percent: wastePercent,
    planned_quantity_kg: totalPlannedQuantityKg,
    order_weight_kg: totalPlannedQuantityKg,
    total_reels: totalReelsCount,
    weight_per_pack_total_kg:
      headerPacks > 0 ? Number((totalPlannedQuantityKg / headerPacks).toFixed(2)) : 0,
    rejection_material: `R-${film}`,
    trim_rule_mode: 'NORMAL',
    min_trim_mm_used: 10,
    max_trim_mm_used: 50,
    duplex_layout: {
      side_a_ups: actualSideAUps,
      side_b_ups: actualSideBUps,
      is_dual_core: false,
      is_dual_length: false,
      side_a_length_m: packLengthM,
      side_b_length_m: packLengthM,
      balance_delta: Math.abs(actualSideAUps - actualSideBUps),
    },
    doc_ref: 'APS/QR/SS/01',
    rev_no: 0,
    issue_date: displayDate,
    items: items,
    changes: [],
    segments: [segment],
    notes: `Mount Jumbo: ${mountJumboWidth} mm | Pack ${packLengthM} m | Packs: ${headerPacks} (from orders_covered; rolls=${jumboRollsCount}) | Source: optimizer orders_covered only (no full-run inflate)`,
  };
}

export const generateMSLSlitterPlan = generateSSSlitterPlan;

/**
 * Generate optimal PS01 Manufacturing Slitter Plans for approved Jumbo Requirements.
 */
export function generatePS01ManufacturingPlansForJumbos(
  requirements: SSJumboRequirement[],
  film: string,
  createdBy: string = 'M.USMAN (Planner)',
  motherDeckleMm?: number
): {
  plans: SlitterPlan[];
  film: string;
  logs: any[];
} {
  if (requirements.length === 0) {
    return { plans: [], film, logs: [] };
  }

  const motherDeckle = [10400, 10330, 8700, 8630].includes(Number(motherDeckleMm))
    ? Number(motherDeckleMm)
    : (DEFAULT_PLANNING_RULES.deckle_width_mm || 10400);
  const thickness = requirements[0]?.thickness_micron || 18;
  const plans: SlitterPlan[] = [];
  let planIndex = 0;
  const logs: any[] = [];

  // 1. Group requirements that already possess a ps01_parent_deckle_id to preserve strict mother run identity
  const parentDeckleGroups = new Map<string, SSJumboRequirement[]>();
  const unparentedReqs: SSJumboRequirement[] = [];

  for (const req of requirements) {
    if (req.ps01_parent_deckle_id) {
      let grp = parentDeckleGroups.get(req.ps01_parent_deckle_id);
      if (!grp) {
        grp = [];
        parentDeckleGroups.set(req.ps01_parent_deckle_id, grp);
      }
      grp.push(req);
    } else {
      unparentedReqs.push(req);
    }
  }

  // Process parent deckle groups with exact mother roll integrity
  for (const [deckleId, groupReqs] of parentDeckleGroups.entries()) {
    planIndex++;
    const decklePlan = generatePS01PlanForDeckleGroup(
      groupReqs,
      planIndex,
      groupReqs[0]?.film || film,
      createdBy,
      motherDeckle
    );
    plans.push(decklePlan);
    logs.push({
      step: logs.length + 1,
      message: `Preserved physical PS01 mother-run '${deckleId}' producing ${decklePlan.total_reels} jumbo rolls across ${decklePlan.repetitions} sets.`,
      type: 'SUCCESS' as const,
    });
  }

  // 2. Process any unparented/ad-hoc requirements using combinatorial search
  if (unparentedReqs.length > 0) {
    interface JumboDemandBucket {
      id: string;
      req: SSJumboRequirement;
      width: number;
      length: number;
      remainingRolls: number;
    }

    const buckets: JumboDemandBucket[] = unparentedReqs.map((req, idx) => ({
      id: req.id || `req-${idx}`,
      req,
      width: req.required_jumbo_width_mm,
      length: req.required_jumbo_length_m,
      remainingRolls: req.required_rolls_count || 1,
    }));

    // Strict parent-deckle-safe consolidation of similar widths (within 15mm)
    for (let i = 0; i < buckets.length; i++) {
      for (let j = i + 1; j < buckets.length; j++) {
        const d1 = buckets[i].req.ps01_parent_deckle_id;
        const d2 = buckets[j].req.ps01_parent_deckle_id;
        const sameDeckle = (d1 && d2) ? d1 === d2 : (!d1 && !d2);
        if (!sameDeckle) continue;

        const diff = Math.abs(buckets[i].width - buckets[j].width);
        if (diff > 0 && diff <= 15) {
          const commonWidth = Math.round((buckets[i].width + buckets[j].width) / 2);
          const trim = motherDeckle - (commonWidth * 3);
          if (trim >= 120 && trim <= 500) {
            const originalI = buckets[i].width;
            const originalJ = buckets[j].width;
            buckets[i].width = commonWidth;
            buckets[j].width = commonWidth;
            buckets[i].req.required_jumbo_width_mm = commonWidth;
            buckets[j].req.required_jumbo_width_mm = commonWidth;
            if (buckets[i].req.ps01_feasibility?.ps01_cut_combination) {
              buckets[i].req.ps01_feasibility!.ps01_cut_combination = buckets[i].req.ps01_feasibility!.ps01_cut_combination.map(w => w === originalI ? commonWidth : w);
            }
            if (buckets[j].req.ps01_feasibility?.ps01_cut_combination) {
              buckets[j].req.ps01_feasibility!.ps01_cut_combination = buckets[j].req.ps01_feasibility!.ps01_cut_combination.map(w => w === originalJ ? commonWidth : w);
            }
            logs.push({
              step: logs.length + 1,
              message: `Consolidated similar jumbo widths (${originalI}mm & ${originalJ}mm) to common width ${commonWidth}mm to reduce PS01 setup changes.`,
              type: 'INFO',
            });
          }
        }
      }
    }

    let activeBuckets = buckets.filter(b => b.remainingRolls > 0);

    while (activeBuckets.length > 0) {
      let bestCombo: {
        b1: JumboDemandBucket;
        b2: JumboDemandBucket;
        b3: JumboDemandBucket;
        b4?: JumboDemandBucket;
        widths: number[];
        ups: number;
        trim: number;
        status: 'GREEN' | 'YELLOW';
        score: number;
        i: number;
        j: number;
        k: number;
        l?: number;
      } | null = null;

      const bLen = activeBuckets.length;
      for (let i = 0; i < bLen; i++) {
        const b1 = activeBuckets[i];
        for (let j = i; j < bLen; j++) {
          const b2 = activeBuckets[j];
          for (let k = j; k < bLen; k++) {
            const b3 = activeBuckets[k];

            const p1 = b1.req.ps01_parent_deckle_id;
            const p2 = b2.req.ps01_parent_deckle_id;
            const p3 = b3.req.ps01_parent_deckle_id;
            const sameParent = (p1 && p2 && p3) ? (p1 === p2 && p2 === p3) : (!p1 && !p2 && !p3);
            if (!sameParent) continue;

            let canForm = false;
            if (i === j && j === k) {
              canForm = b1.remainingRolls >= 3;
            } else if (i === j) {
              canForm = b1.remainingRolls >= 2 && b3.remainingRolls >= 1;
            } else if (j === k) {
              canForm = b1.remainingRolls >= 1 && b2.remainingRolls >= 2;
            } else {
              canForm = b1.remainingRolls >= 1 && b2.remainingRolls >= 1 && b3.remainingRolls >= 1;
            }

            if (!canForm) continue;

            const widths = [b1.width, b2.width, b3.width];
            const evalResult = evaluatePS01CombinationFeasibility(widths, film, thickness);

            if (evalResult.is_feasible && evalResult.status !== 'RED') {
              let score = 20000;
              if (evalResult.status === 'GREEN') score += 5000;
              score -= Math.abs(evalResult.ps01_trim_mm - 190);
              if (b1.width === b2.width && b2.width === b3.width) score += 2000;
              else if (b1.width === b2.width || b2.width === b3.width || b1.width === b3.width) score += 1000;

              if (!bestCombo || score > bestCombo.score) {
                bestCombo = {
                  b1,
                  b2,
                  b3,
                  widths,
                  ups: 3,
                  trim: evalResult.ps01_trim_mm,
                  status: evalResult.status,
                  score,
                  i,
                  j,
                  k,
                };
              }
            }
          }
        }
      }

      if (!bestCombo) {
        for (let i = 0; i < bLen; i++) {
          const b1 = activeBuckets[i];
          for (let j = i; j < bLen; j++) {
            const b2 = activeBuckets[j];
            for (let k = j; k < bLen; k++) {
              const b3 = activeBuckets[k];
              for (let l = k; l < bLen; l++) {
                const b4 = activeBuckets[l];

                const p1 = b1.req.ps01_parent_deckle_id;
                const p2 = b2.req.ps01_parent_deckle_id;
                const p3 = b3.req.ps01_parent_deckle_id;
                const p4 = b4.req.ps01_parent_deckle_id;
                const sameParent = (p1 && p2 && p3 && p4) ? (p1 === p2 && p2 === p3 && p3 === p4) : (!p1 && !p2 && !p3 && !p4);
                if (!sameParent) continue;

                const counts: Record<number, number> = {};
                counts[i] = (counts[i] || 0) + 1;
                counts[j] = (counts[j] || 0) + 1;
                counts[k] = (counts[k] || 0) + 1;
                counts[l] = (counts[l] || 0) + 1;

                const canForm = Object.entries(counts).every(([idx, needed]) => activeBuckets[Number(idx)].remainingRolls >= needed);
                if (!canForm) continue;

                const widths = [b1.width, b2.width, b3.width, b4.width];
                const evalResult = evaluatePS01CombinationFeasibility(widths, film, thickness);

                if (evalResult.is_feasible && evalResult.status !== 'RED') {
                  let score = 10000;
                  if (evalResult.status === 'GREEN') score += 3000;
                  score -= Math.abs(evalResult.ps01_trim_mm - 190);

                  if (!bestCombo || score > bestCombo.score) {
                    bestCombo = {
                      b1,
                      b2,
                      b3,
                      b4,
                      widths,
                      ups: 4,
                      trim: evalResult.ps01_trim_mm,
                      status: evalResult.status,
                      score,
                      i,
                      j,
                      k,
                      l,
                    };
                  }
                }
              }
            }
          }
        }
      }

      if (bestCombo) {
        const { b1, b2, b3, b4, widths, ups, i, j, k, l } = bestCombo;
        let batchCycles = Infinity;

        if (ups === 3) {
          if (i === j && j === k) {
            batchCycles = Math.floor(b1.remainingRolls / 3);
          } else if (i === j) {
            batchCycles = Math.min(Math.floor(b1.remainingRolls / 2), b3.remainingRolls);
          } else if (j === k) {
            batchCycles = Math.min(b1.remainingRolls, Math.floor(b2.remainingRolls / 2));
          } else {
            batchCycles = Math.min(b1.remainingRolls, b2.remainingRolls, b3.remainingRolls);
          }
        } else if (ups === 4 && b4 !== undefined && l !== undefined) {
          const counts: Record<number, number> = {};
          counts[i] = (counts[i] || 0) + 1;
          counts[j] = (counts[j] || 0) + 1;
          counts[k] = (counts[k] || 0) + 1;
          counts[l] = (counts[l] || 0) + 1;
          for (const [idx, needed] of Object.entries(counts)) {
            const avail = Math.floor(activeBuckets[Number(idx)].remainingRolls / needed);
            if (avail < batchCycles) batchCycles = avail;
          }
        }

        batchCycles = Math.max(1, batchCycles);
        const reqs = ups === 3 ? [b1.req, b2.req, b3.req] : [b1.req, b2.req, b3.req, b4!.req];
        const maxLen = Math.max(...(ups === 3 ? [b1.length, b2.length, b3.length] : [b1.length, b2.length, b3.length, b4!.length]));

        for (let c = 0; c < batchCycles; c++) {
          const plan = generatePS01PlanForJumboCombination(
            widths,
            planIndex++,
            film,
            maxLen,
            thickness,
            reqs,
            createdBy,
            1,
            motherDeckle
          );
          plans.push(plan);
        }

        if (ups === 3) {
          if (i === j && j === k) {
            b1.remainingRolls -= 3 * batchCycles;
          } else if (i === j) {
            b1.remainingRolls -= 2 * batchCycles;
            b3.remainingRolls -= batchCycles;
          } else if (j === k) {
            b1.remainingRolls -= batchCycles;
            b2.remainingRolls -= 2 * batchCycles;
          } else {
            b1.remainingRolls -= batchCycles;
            b2.remainingRolls -= batchCycles;
            b3.remainingRolls -= batchCycles;
          }
        } else if (ups === 4 && l !== undefined) {
          const counts: Record<number, number> = {};
          counts[i] = (counts[i] || 0) + 1;
          counts[j] = (counts[j] || 0) + 1;
          counts[k] = (counts[k] || 0) + 1;
          counts[l] = (counts[l] || 0) + 1;
          for (const [idx, needed] of Object.entries(counts)) {
            activeBuckets[Number(idx)].remainingRolls -= needed * batchCycles;
          }
        }

        activeBuckets = activeBuckets.filter(b => b.remainingRolls > 0);
      } else {
        while (activeBuckets.length > 0) {
          const singleBucket = activeBuckets[0];
          const parentDeckleId = singleBucket.req.ps01_parent_deckle_id;
          const feasibilityCuts = singleBucket.req.ps01_feasibility?.ps01_cut_combination;

          const siblingBuckets = parentDeckleId
            ? activeBuckets.filter(b => b.req.ps01_parent_deckle_id === parentDeckleId)
            : [singleBucket];

          if (siblingBuckets.length > 1 && feasibilityCuts && feasibilityCuts.length > 0) {
            const matchedBuckets: JumboDemandBucket[] = [];
            const matchedWidths: number[] = [];
            const tempRemaining = new Map<string, number>();
            for (const b of siblingBuckets) tempRemaining.set(b.id, b.remainingRolls);

            for (const cutW of feasibilityCuts) {
              const match = siblingBuckets.find(b => {
                const rem = tempRemaining.get(b.id) || 0;
                return rem > 0 && Math.abs(b.width - cutW) <= 15;
              });
              if (match) {
                matchedBuckets.push(match);
                matchedWidths.push(cutW);
                tempRemaining.set(match.id, (tempRemaining.get(match.id) || 0) - 1);
              }
            }

            if (matchedBuckets.length > 0) {
              const plan = generatePS01PlanForJumboCombination(
                matchedWidths,
                planIndex++,
                singleBucket.req.film || film,
                singleBucket.length,
                singleBucket.req.thickness_micron || thickness,
                matchedBuckets.map(b => b.req),
                createdBy,
                1,
                motherDeckle
              );
              plans.push(plan);
              for (const mb of matchedBuckets) {
                mb.remainingRolls -= 1;
              }
              activeBuckets = activeBuckets.filter(b => b.remainingRolls > 0);
              continue;
            }
          }

          for (let r = 0; r < singleBucket.remainingRolls; r++) {
            const singlePlan = generatePS01PlanForJumboCombination(
              [singleBucket.width],
              planIndex++,
              singleBucket.req.film || film,
              singleBucket.length,
              singleBucket.req.thickness_micron || thickness,
              [singleBucket.req],
              createdBy,
              1,
              motherDeckle
            );
            plans.push(singlePlan);
          }
          singleBucket.remainingRolls = 0;
          activeBuckets = activeBuckets.filter(b => b.remainingRolls > 0);
        }
        break;
      }
    }
  }

  // 3. Hard quantity and width-wise reconciliation guard across entire campaign
  const allMfgRolls: { width_mm: number; count: number; film?: string; length_m?: number; parent_deckle_id?: string; source_requirement_id?: string }[] = [];
  for (const p of plans) {
    const sets = p.repetitions || 1;
    for (const cut of p.items) {
      allMfgRolls.push({
        width_mm: cut.width_mm,
        count: sets,
        film: cut.film || p.film,
        length_m: cut.length_m,
        parent_deckle_id: cut.parent_deckle_id,
        source_requirement_id: cut.source_requirement_id,
      });
    }
  }

  const campaignReconciliation = validateSSWidthWiseJumboReconciliation(allMfgRolls, requirements);
  if (!campaignReconciliation.is_valid) {
    // Surgical: allow ceiling surplus (full PS01 UPS packs); only hard-fail on shortage
    const onlySurplus = campaignReconciliation.errors.every(
      e => typeof e === 'string' && (e.includes('unallocated rolls') || e.includes('only consumes'))
    );
    const filmKey = String(film || '').toUpperCase();
    const isFixed1705Campaign =
      filmKey === 'MATTPL12' ||
      filmKey === 'TNBPL10' ||
      requirements.every(r => r.required_jumbo_width_mm === 1705);

    if (!(onlySurplus || isFixed1705Campaign)) {
      throw new Error(
        `PS01 Campaign Width-Wise Quantity Reconciliation Guard Violation:\n${campaignReconciliation.errors.join('\n')}`
      );
    }
    logs.push({
      step: logs.length + 1,
      message: `Reconciliation note (non-blocking): ${campaignReconciliation.errors.join('; ')}`,
      type: 'WARNING' as const,
    });
  }

  logs.push({
    step: logs.length + 1,
    message: `Generated ${plans.length} optimized PS01 Manufacturing Plan(s) for ${film} jumbo rolls with isolated Factory Sheets. Minimized setups and waste.`,
    type: 'SUCCESS' as const,
    data: { planCount: plans.length },
  });

  return {
    plans,
    film,
    logs,
  };
}

export function generatePS01ManufacturingPlanForJumbos(
  requirements: SSJumboRequirement[],
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): {
  plans: SlitterPlan[];
  film: string;
  logs: any[];
} {
  return generatePS01ManufacturingPlansForJumbos(requirements, film, createdBy, undefined);
}
