/**
 * GPAK MSL <-> PS01 Feasibility Handshake Adapter
 *
 * CRITICAL ARCHITECTURAL CONSTRAINTS:
 * - PS01 Primary Slitter optimizer is 100% FROZEN.
 * - This adapter acts as a non-invasive bridge to evaluate whether candidate
 *   Jumbo Roll requirements generated by MSL are physically and mathematically
 *   manufacturable on PS01 (10,400 mm mother deckle, 140-250 mm normal trim, duplex balance).
 * - Implements strict Priority Ordering for Trim Relaxation (Last Resort Only):
 *   Priority A: Normal MSL trim (20-30mm) + Normal PS01 rules (140-250mm) -> GREEN
 *   Priority B: Explore all viable combination permutations
 *   Priority C: MSL Trim adjustment within [20, 30] mm -> YELLOW (MSL_TRIM_ADJUSTED)
 *   Priority D/E: Upstream PS01 Trim relaxation -> YELLOW (PS01_TRIM_RELAXED)
 *   Otherwise: RED (Infeasible)
 */
import { VA05Order, SlitterPlan } from '../../types';
import { JumboRequirement } from '../../types/metallizer';
export type PS01HandshakeStatus = 'GREEN' | 'YELLOW' | 'RED';
export type TrimRelaxationType = 'NONE' | 'MSL_TRIM_ADJUSTED' | 'PS01_TRIM_RELAXED';
export interface PS01FeasibilityEvaluation {
    status: PS01HandshakeStatus;
    is_feasible: boolean;
    ps01_deckle_mm: number;
    jumbo_width_mm: number;
    ps01_ups: number;
    ps01_cut_combination: number[];
    ps01_total_width_mm: number;
    ps01_trim_mm: number;
    ps01_deckle_efficiency_percent: number;
    ps01_duplex_balanced: boolean;
    side_a_ups: number;
    side_b_ups: number;
    relaxation_type: TrimRelaxationType;
    relaxation_flag?: string;
    explanation: string;
}
export interface CandidateJumboProposal {
    film: string;
    thickness_micron: number;
    finished_widths: number[];
    msl_ups: number;
    target_msl_trim_mm: number;
    jumbo_width_mm: number;
    package_length_m: number;
    package_multiple: number;
    jumbo_length_m: number;
    diameter_mm: number;
    matching_orders: VA05Order[];
}
/**
 * Evaluate multi-width PS01 combination feasibility (e.g. [3385, 3425, 3385] mm)
 * Strictly enforces:
 * - 3-UPS preferred
 * - 4-UPS maximum
 * - 5/6-UPS strictly forbidden (RED)
 * - Standard PS01 trim for MSL: 140–250 mm (GREEN)
 * - Relaxed PS01 trim: 120–500 mm (YELLOW)
 */
export declare function evaluatePS01CombinationFeasibility(widths: number[], film: string, thicknessMicron?: number): PS01FeasibilityEvaluation;
/**
 * Perform non-invasive PS01 Feasibility Handshake for a proposed Jumbo Width
 */
export declare function evaluatePS01Feasibility(jumboWidthMm: number, film: string, thicknessMicron: number, finishedWidths?: number[], baseMslTrimMm?: number): PS01FeasibilityEvaluation;
/**
 * Generate a separate, authoritative PS01 SlitterPlan for an INDIVIDUAL Jumbo Roll Plan or multi-width jumbo combination.
 * STRICT REQUIREMENT: Each Jumbo Plan has its own isolated Factory Sheet with NO cross-plan data mixing.
 */
export declare function generatePS01PlanForJumboCombination(jumboWidths: number[], planIndex: number, film: string, lengthM: number, thickness?: number, associatedReqs?: JumboRequirement[], createdBy?: string, repetitions?: number): SlitterPlan;
/**
 * Generate a separate, authoritative PS01 SlitterPlan for a complete Mother Roll Deckle Run Group.
 * This accurately calculates:
 * 1. The exact Number of Mother Roll Packs (Sets / Repetitions) required to satisfy all physical rolls.
 * 2. The proper length (m) of the Jumbo Mother Rolls.
 * 3. Accurate Knife cut allocations to each downstream Metallizer (MSL) Plan.
 */
export declare function generatePS01PlanForDeckleGroup(reqs: JumboRequirement[], runIndex: number, film: string, createdBy?: string): SlitterPlan;
/**
 * Generate a separate, authoritative PS01 SlitterPlan for an INDIVIDUAL Jumbo Roll Plan.
 * STRICT REQUIREMENT: Each Jumbo Plan has its own isolated Factory Sheet with NO cross-plan data mixing.
 */
export declare function generatePS01PlanForSingleJumbo(req: JumboRequirement, planIndex: number, film: string, createdBy?: string): SlitterPlan;
/**
 * Generate a customer-standard SlitterPlan for a Metallizer Slitter (MSL) Plan.
 * This formats the MSL slitting job in the standard BOPP factory sheet layout (PlanDetailViewer),
 * with duplex arms, knife positions, customer sales orders, roll repetitions (packs),
 * jumbo mount width, trim waste, and quality checks.
 */
export declare function generateMSLSlitterPlan(req: JumboRequirement, planIndex: number, film: string, createdBy?: string): SlitterPlan;
/**
 * Generate optimal PS01 Manufacturing Slitter Plans for approved Jumbo Requirements.
 * CRITICAL OPTIMIZATION RULES:
 * 1. Minimizes unnecessary jumbo-roll manufacturing and maximizes usable jumbo length.
 * 2. Allows different jumbo widths in the same 3-UPS or 4-UPS PS01 pattern (e.g. 3385 + 3425 + 3385 mm).
 * 3. 3-UPS is preferred; 4-UPS is maximum; 5/6-UPS are strictly forbidden.
 * 4. Intelligently consolidates similar jumbo widths (within 15mm) to reduce PS01 knife setups.
 * 5. Guarantees every individual jumbo-roll manufacturing plan maintains its own separate Factory Sheet.
 */
export declare function generatePS01ManufacturingPlansForJumbos(requirements: JumboRequirement[], film: string, createdBy?: string): {
    plans: SlitterPlan[];
    film: string;
    logs: any[];
};
/**
 * Backward compatibility alias
 */
export declare function generatePS01ManufacturingPlanForJumbos(requirements: JumboRequirement[], film: string, createdBy?: string): {
    plans: SlitterPlan[];
    film: string;
    logs: any[];
};
/**
 * Consolidate identical 1-set PS01 manufacturing plans into unified repetition tickets.
 */
export declare function consolidatePS01Plans(plans: SlitterPlan[]): SlitterPlan[];

