/**
 * GPAK MSL <-> PS01 Feasibility Handshake Adapter
 * 
 * CRITICAL ARCHITECTURAL CONSTRAINTS:
 * - PS01 Primary Slitter optimizer is 100% FROZEN.
 * - This adapter acts as a non-invasive bridge to evaluate whether candidate
 *   Jumbo Roll requirements generated by MSL are physically and mathematically
 *   manufacturable on PS01 (10,400 mm mother deckle, 150-280 mm normal trim, duplex balance).
 * - Implements strict Priority Ordering for Trim Relaxation (Last Resort Only):
 *   Priority A: Normal MSL trim (18-45mm) + Normal PS01 rules (150-280mm) -> GREEN
 *   Priority B: Explore all viable combination permutations
 *   Priority C: MSL Trim adjustment within [18, 45] mm -> YELLOW (MSL_TRIM_ADJUSTED)
 *   Priority D/E: Upstream PS01 Trim relaxation (281-500mm) -> YELLOW (PS01_TRIM_RELAXED)
 *   Otherwise: RED (Infeasible: <150mm or >500mm)
 */

import { DEFAULT_PLANNING_RULES } from '../masterData';
import { VA05Order, SlitterPlan, PlanItem, PlanSegment, PlanChange } from '../../types';
import { generatePrimarySlitterPlans, OptimizationResult } from '../optimizer/deckleOptimizer';
import { JumboRequirement } from '../../types/metallizer';

export type PS01HandshakeStatus = 'GREEN' | 'YELLOW' | 'RED';
export type TrimRelaxationType = 'NONE' | 'MSL_TRIM_ADJUSTED' | 'PS01_TRIM_RELAXED';

export interface PS01FeasibilityEvaluation {
  status: PS01HandshakeStatus;
  is_feasible: boolean;
  ps01_deckle_mm: number;
  jumbo_width_mm: number;
  ps01_ups: number;
  ps01_cut_combination: number[];
  ps01_total_width_mm: number;
  ps01_trim_mm: number;
  ps01_deckle_efficiency_percent: number;
  ps01_duplex_balanced: boolean;
  side_a_ups: number;
  side_b_ups: number;
  relaxation_type: TrimRelaxationType;
  relaxation_flag?: string;
  explanation: string;
}

export interface CandidateJumboProposal {
  film: string;
  thickness_micron: number;
  finished_widths: number[];
  msl_ups: number;
  target_msl_trim_mm: number;
  jumbo_width_mm: number;
  package_length_m: number;
  package_multiple: number;
  jumbo_length_m: number;
  diameter_mm: number;
  matching_orders: VA05Order[];
}

// Memoization caches for high-speed deterministic feasibility queries
const comboFeasibilityCache = new Map<string, PS01FeasibilityEvaluation>();
const singleFeasibilityCache = new Map<string, PS01FeasibilityEvaluation>();

/**
 * Evaluate multi-width PS01 combination feasibility (e.g. [3385, 3425, 3385] mm)
 * Strictly enforces:
 * - 3-UPS preferred
 * - 4-UPS maximum
 * - 5/6-UPS strictly forbidden (RED)
 * - Standard PS01 trim for MSL: 150–280 mm (GREEN)
 * - Relaxed PS01 trim: 281–500 mm (YELLOW)
 * - Infeasible trim: < 150 mm or > 500 mm (RED)
 */
export function evaluatePS01CombinationFeasibility(
  widths: number[],
  film: string,
  thicknessMicron: number = 18
): PS01FeasibilityEvaluation {
  const cacheKey = `${film}:${thicknessMicron}:${widths.join(',')}`;
  const cached = comboFeasibilityCache.get(cacheKey);
  if (cached) return cached;

  const motherDeckle = DEFAULT_PLANNING_RULES.deckle_width_mm || 10400;
  const normalMinTrim = DEFAULT_PLANNING_RULES.min_trim_mm || 150;
  const normalMaxTrim = DEFAULT_PLANNING_RULES.max_trim_mm || 280;
  const ps01Ups = widths.length;

  // HARD CONSTRAINT: 5/6 UPS are strictly forbidden on PS01
  if (ps01Ups > 4 || ps01Ups < 1) {
    const res: PS01FeasibilityEvaluation = {
      status: 'RED',
      is_feasible: false,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.round(widths.reduce((a, b) => a + b, 0) / Math.max(1, ps01Ups)),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: widths.reduce((a, b) => a + b, 0),
      ps01_trim_mm: 0,
      ps01_deckle_efficiency_percent: 0,
      ps01_duplex_balanced: false,
      side_a_ups: 0,
      side_b_ups: 0,
      relaxation_type: 'NONE',
      explanation: `PS01 upstream jumbo manufacturing strictly forbids ${ps01Ups}-UPS (allowed: 3-UPS preferred, 4-UPS maximum)`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Check any individual width against MSL max limit
  if (widths.some(w => w > 3650)) {
    const res: PS01FeasibilityEvaluation = {
      status: 'RED',
      is_feasible: false,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.max(...widths),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: widths.reduce((a, b) => a + b, 0),
      ps01_trim_mm: 0,
      ps01_deckle_efficiency_percent: 0,
      ps01_duplex_balanced: false,
      side_a_ups: 0,
      side_b_ups: 0,
      relaxation_type: 'NONE',
      explanation: `One or more jumbo widths exceed MSL maximum limit of 3650 mm`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  const totalSlitWidth = widths.reduce((a, b) => a + b, 0);
  const ps01Trim = motherDeckle - totalSlitWidth;
  const sideAUps = Math.ceil(ps01Ups / 2);
  const sideBUps = Math.floor(ps01Ups / 2);
  const isDuplexBalanced = Math.abs(sideAUps - sideBUps) <= 1;
  const efficiency = Number(((totalSlitWidth / motherDeckle) * 100).toFixed(2));
  const cutDesc = widths.join(' + ') + ` mm = ${totalSlitWidth} mm`;

  // Standard PS01 trim (150 - 280 mm) -> GREEN
  if (ps01Trim >= normalMinTrim && ps01Trim <= normalMaxTrim) {
    const res: PS01FeasibilityEvaluation = {
      status: 'GREEN',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.round(totalSlitWidth / ps01Ups),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: totalSlitWidth,
      ps01_trim_mm: ps01Trim,
      ps01_deckle_efficiency_percent: efficiency,
      ps01_duplex_balanced: isDuplexBalanced,
      side_a_ups: sideAUps,
      side_b_ups: sideBUps,
      relaxation_type: 'NONE',
      explanation: `${ps01Ups === 3 ? 'Preferred 3-UPS' : '4-UPS'} multi-width jumbo pattern on PS01 (${cutDesc}, PS01 Trim: ${ps01Trim}mm within standard ${normalMinTrim}–${normalMaxTrim}mm)`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Relaxed PS01 trim (281 - 500 mm) -> YELLOW
  if (ps01Trim > normalMaxTrim && ps01Trim <= 500) {
    const res: PS01FeasibilityEvaluation = {
      status: 'YELLOW',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: Math.round(totalSlitWidth / ps01Ups),
      ps01_ups: ps01Ups,
      ps01_cut_combination: widths,
      ps01_total_width_mm: totalSlitWidth,
      ps01_trim_mm: ps01Trim,
      ps01_deckle_efficiency_percent: efficiency,
      ps01_duplex_balanced: isDuplexBalanced,
      side_a_ups: sideAUps,
      side_b_ups: sideBUps,
      relaxation_type: 'PS01_TRIM_RELAXED',
      relaxation_flag: `NON-STANDARD PS01 TRIM: Upstream trim relaxed to ${ps01Trim} mm (standard: ${normalMinTrim}–${normalMaxTrim} mm) for ${ps01Ups}-UPS multi-width pattern`,
      explanation: `Feasible via PS01 Trim Relaxation (${ps01Ups}-UPS): ${cutDesc}, PS01 Trim = ${ps01Trim}mm within allowed relaxation envelope (281–500 mm)`,
    };
    comboFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Infeasible (< 150 mm or > 500 mm) -> RED
  const redRes: PS01FeasibilityEvaluation = {
    status: 'RED',
    is_feasible: false,
    ps01_deckle_mm: motherDeckle,
    jumbo_width_mm: Math.round(totalSlitWidth / ps01Ups),
    ps01_ups: ps01Ups,
    ps01_cut_combination: widths,
    ps01_total_width_mm: totalSlitWidth,
    ps01_trim_mm: ps01Trim,
    ps01_deckle_efficiency_percent: efficiency,
    ps01_duplex_balanced: isDuplexBalanced,
    side_a_ups: sideAUps,
    side_b_ups: sideBUps,
    relaxation_type: 'NONE',
    explanation: `Cannot manufacture combination on PS01: ${cutDesc}, resulting in invalid trim of ${ps01Trim} mm (strictly requires 150–500 mm envelope; trim < 150 mm or > 500 mm is RED)`,
  };
  comboFeasibilityCache.set(cacheKey, redRes);
  return redRes;
}

/**
 * Perform non-invasive PS01 Feasibility Handshake for a proposed Jumbo Width
 */
export function evaluatePS01Feasibility(
  jumboWidthMm: number,
  film: string,
  thicknessMicron: number,
  finishedWidths: number[] = [],
  baseMslTrimMm: number = 25
): PS01FeasibilityEvaluation {
  const cacheKey = `${film}:${thicknessMicron}:${jumboWidthMm}:${finishedWidths.join(',')}:${baseMslTrimMm}`;
  const cached = singleFeasibilityCache.get(cacheKey);
  if (cached) return cached;

  const motherDeckle = DEFAULT_PLANNING_RULES.deckle_width_mm || 10400;
  const normalMinTrim = DEFAULT_PLANNING_RULES.min_trim_mm || 150;
  const normalMaxTrim = DEFAULT_PLANNING_RULES.max_trim_mm || 280;

  // Enforce MSL hard limit on Jumbo Width
  if (jumboWidthMm > 3650) {
    const res: PS01FeasibilityEvaluation = {
      status: 'RED',
      is_feasible: false,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 0,
      ps01_cut_combination: [],
      ps01_total_width_mm: 0,
      ps01_trim_mm: 0,
      ps01_deckle_efficiency_percent: 0,
      ps01_duplex_balanced: false,
      side_a_ups: 0,
      side_b_ups: 0,
      relaxation_type: 'NONE',
      explanation: `Jumbo width ${jumboWidthMm} mm exceeds MSL maximum limit of 3650 mm`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // -------------------------------------------------------------------------
  // PRIORITY 1: 3-UPS on PS01 (First Priority for Upstream Jumbo Manufacturing)
  // PRIORITY 2: 4-UPS on PS01 (Second Priority / Maximum allowed on PS01)
  // 5-UPS and 6-UPS are STRICTLY FORBIDDEN for jumbo manufacturing on PS01
  // -------------------------------------------------------------------------

  // --- Step 1: Normal PS01 Standard Trim (150 - 280 mm) ---
  // Priority 1: 3-UPS
  const totalSlit3 = jumboWidthMm * 3;
  const ps01Trim3 = motherDeckle - totalSlit3;
  if (ps01Trim3 >= normalMinTrim && ps01Trim3 <= normalMaxTrim) {
    const res: PS01FeasibilityEvaluation = {
      status: 'GREEN',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 3,
      ps01_cut_combination: [jumboWidthMm, jumboWidthMm, jumboWidthMm],
      ps01_total_width_mm: totalSlit3,
      ps01_trim_mm: ps01Trim3,
      ps01_deckle_efficiency_percent: Number(((totalSlit3 / motherDeckle) * 100).toFixed(2)),
      ps01_duplex_balanced: true,
      side_a_ups: 2,
      side_b_ups: 1,
      relaxation_type: 'NONE',
      explanation: `Preferred 3-UPS jumbo manufacturing pattern on PS01 (3×${jumboWidthMm}mm = ${totalSlit3}mm, PS01 Trim: ${ps01Trim3}mm within standard ${normalMinTrim}–${normalMaxTrim}mm)`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Priority 2: 4-UPS (Only if 3-UPS is infeasible)
  const totalSlit4 = jumboWidthMm * 4;
  const ps01Trim4 = motherDeckle - totalSlit4;
  if (ps01Trim4 >= normalMinTrim && ps01Trim4 <= normalMaxTrim) {
    const res: PS01FeasibilityEvaluation = {
      status: 'GREEN',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 4,
      ps01_cut_combination: [jumboWidthMm, jumboWidthMm, jumboWidthMm, jumboWidthMm],
      ps01_total_width_mm: totalSlit4,
      ps01_trim_mm: ps01Trim4,
      ps01_deckle_efficiency_percent: Number(((totalSlit4 / motherDeckle) * 100).toFixed(2)),
      ps01_duplex_balanced: true,
      side_a_ups: 2,
      side_b_ups: 2,
      relaxation_type: 'NONE',
      explanation: `Feasible 4-UPS jumbo manufacturing pattern on PS01 (4×${jumboWidthMm}mm = ${totalSlit4}mm, PS01 Trim: ${ps01Trim4}mm within standard ${normalMinTrim}–${normalMaxTrim}mm)`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // -------------------------------------------------------------------------
  // PRIORITY C: MSL-side Trim Adjustment (Within 20–40 mm standard window)
  // Check 3-UPS first, then 4-UPS maximum
  // -------------------------------------------------------------------------
  if (finishedWidths.length > 0) {
    const sumFinished = finishedWidths.reduce((a, b) => a + b, 0);

    // 1. Check 3-UPS with MSL trim adjustment (Within 18–45 mm plant-approved window)
    for (let testMslTrim = 18; testMslTrim <= 45; testMslTrim++) {
      if (testMslTrim === baseMslTrimMm) continue;
      const adjustedJumboWidth = sumFinished + testMslTrim;
      if (adjustedJumboWidth > 3650) continue;

      const totalSlit = adjustedJumboWidth * 3;
      const ps01Trim = motherDeckle - totalSlit;
      if (ps01Trim >= normalMinTrim && ps01Trim <= normalMaxTrim) {
        const res: PS01FeasibilityEvaluation = {
          status: 'YELLOW',
          is_feasible: true,
          ps01_deckle_mm: motherDeckle,
          jumbo_width_mm: adjustedJumboWidth,
          ps01_ups: 3,
          ps01_cut_combination: [adjustedJumboWidth, adjustedJumboWidth, adjustedJumboWidth],
          ps01_total_width_mm: totalSlit,
          ps01_trim_mm: ps01Trim,
          ps01_deckle_efficiency_percent: Number(((totalSlit / motherDeckle) * 100).toFixed(2)),
          ps01_duplex_balanced: true,
          side_a_ups: 2,
          side_b_ups: 1,
          relaxation_type: 'MSL_TRIM_ADJUSTED',
          relaxation_flag: `NON-STANDARD MSL TRIM: Adjusted to ${testMslTrim} mm (within 18–45 mm window) to enable preferred 3-UPS on PS01`,
          explanation: `Feasible via MSL trim adjustment to ${testMslTrim}mm -> Preferred 3-UPS on PS01 (3×${adjustedJumboWidth}mm = ${totalSlit}mm, PS01 Trim: ${ps01Trim}mm)`,
        };
        singleFeasibilityCache.set(cacheKey, res);
        return res;
      }
    }

    // 2. Check 4-UPS with MSL trim adjustment (if 3-UPS impossible)
    for (let testMslTrim = 18; testMslTrim <= 45; testMslTrim++) {
      if (testMslTrim === baseMslTrimMm) continue;
      const adjustedJumboWidth = sumFinished + testMslTrim;
      if (adjustedJumboWidth > 3650) continue;

      const totalSlit = adjustedJumboWidth * 4;
      const ps01Trim = motherDeckle - totalSlit;
      if (ps01Trim >= normalMinTrim && ps01Trim <= normalMaxTrim) {
        const res: PS01FeasibilityEvaluation = {
          status: 'YELLOW',
          is_feasible: true,
          ps01_deckle_mm: motherDeckle,
          jumbo_width_mm: adjustedJumboWidth,
          ps01_ups: 4,
          ps01_cut_combination: [adjustedJumboWidth, adjustedJumboWidth, adjustedJumboWidth, adjustedJumboWidth],
          ps01_total_width_mm: totalSlit,
          ps01_trim_mm: ps01Trim,
          ps01_deckle_efficiency_percent: Number(((totalSlit / motherDeckle) * 100).toFixed(2)),
          ps01_duplex_balanced: true,
          side_a_ups: 2,
          side_b_ups: 2,
          relaxation_type: 'MSL_TRIM_ADJUSTED',
          relaxation_flag: `NON-STANDARD MSL TRIM: Adjusted to ${testMslTrim} mm (within 18–45 mm window) to enable 4-UPS on PS01`,
          explanation: `Feasible via MSL trim adjustment to ${testMslTrim}mm -> 4-UPS on PS01 (4×${adjustedJumboWidth}mm = ${totalSlit}mm, PS01 Trim: ${ps01Trim}mm)`,
        };
        singleFeasibilityCache.set(cacheKey, res);
        return res;
      }
    }
  }

  // -------------------------------------------------------------------------
  // PRIORITY D & E: Upstream PS01-side Trim Relaxation (Yellow 281 - 500 mm window)
  // Check 3-UPS first, then 4-UPS maximum (5/6-UPS strictly forbidden)
  // -------------------------------------------------------------------------
  // 1. Check 3-UPS under relaxed PS01 trim
  if (ps01Trim3 >= 281 && ps01Trim3 <= 500) {
    const res: PS01FeasibilityEvaluation = {
      status: 'YELLOW',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 3,
      ps01_cut_combination: [jumboWidthMm, jumboWidthMm, jumboWidthMm],
      ps01_total_width_mm: totalSlit3,
      ps01_trim_mm: ps01Trim3,
      ps01_deckle_efficiency_percent: Number(((totalSlit3 / motherDeckle) * 100).toFixed(2)),
      ps01_duplex_balanced: true,
      side_a_ups: 2,
      side_b_ups: 1,
      relaxation_type: 'PS01_TRIM_RELAXED',
      relaxation_flag: `NON-STANDARD PS01 TRIM: Upstream trim relaxed to ${ps01Trim3} mm (standard: ${normalMinTrim}–${normalMaxTrim} mm) for 3-UPS`,
      explanation: `Feasible via Upstream PS01 Trim Relaxation (3-UPS): 3×${jumboWidthMm}mm = ${totalSlit3}mm, PS01 Trim = ${ps01Trim3}mm`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // 2. Check 4-UPS under relaxed PS01 trim
  if (ps01Trim4 >= 281 && ps01Trim4 <= 500) {
    const res: PS01FeasibilityEvaluation = {
      status: 'YELLOW',
      is_feasible: true,
      ps01_deckle_mm: motherDeckle,
      jumbo_width_mm: jumboWidthMm,
      ps01_ups: 4,
      ps01_cut_combination: [jumboWidthMm, jumboWidthMm, jumboWidthMm, jumboWidthMm],
      ps01_total_width_mm: totalSlit4,
      ps01_trim_mm: ps01Trim4,
      ps01_deckle_efficiency_percent: Number(((totalSlit4 / motherDeckle) * 100).toFixed(2)),
      ps01_duplex_balanced: true,
      side_a_ups: 2,
      side_b_ups: 2,
      relaxation_type: 'PS01_TRIM_RELAXED',
      relaxation_flag: `NON-STANDARD PS01 TRIM: Upstream trim relaxed to ${ps01Trim4} mm (standard: ${normalMinTrim}–${normalMaxTrim} mm) for 4-UPS`,
      explanation: `Feasible via Upstream PS01 Trim Relaxation (4-UPS): 4×${jumboWidthMm}mm = ${totalSlit4}mm, PS01 Trim = ${ps01Trim4}mm`,
    };
    singleFeasibilityCache.set(cacheKey, res);
    return res;
  }

  // Otherwise completely infeasible (5/6-UPS forbidden on PS01)
  const finalRedRes: PS01FeasibilityEvaluation = {
    status: 'RED',
    is_feasible: false,
    ps01_deckle_mm: motherDeckle,
    jumbo_width_mm: jumboWidthMm,
    ps01_ups: 0,
    ps01_cut_combination: [],
    ps01_total_width_mm: 0,
    ps01_trim_mm: 0,
    ps01_deckle_efficiency_percent: 0,
    ps01_duplex_balanced: false,
    side_a_ups: 0,
    side_b_ups: 0,
    relaxation_type: 'NONE',
    explanation: `Cannot manufacture jumbo width ${jumboWidthMm} mm on PS01: 3-UPS and 4-UPS are infeasible, and 5/6-UPS are strictly forbidden for upstream jumbo roll manufacturing (10,400 mm master deckle)`,
  };
  singleFeasibilityCache.set(cacheKey, finalRedRes);
  return finalRedRes;
}

/**
 * Generate a separate, authoritative PS01 SlitterPlan for an INDIVIDUAL Jumbo Roll Plan or multi-width jumbo combination.
 * STRICT REQUIREMENT: Each Jumbo Plan has its own isolated Factory Sheet with NO cross-plan data mixing.
 */
export function generatePS01PlanForJumboCombination(
  jumboWidths: number[],
  planIndex: number,
  film: string,
  lengthM: number,
  thickness: number = 18,
  associatedReqs: JumboRequirement[] = [],
  createdBy: string = 'M.USMAN (Planner)',
  repetitions: number = 1
): SlitterPlan {
  const motherDeckle = DEFAULT_PLANNING_RULES.deckle_width_mm || 10400;
  const ps01Ups = jumboWidths.length;
  const sideAUps = Math.ceil(ps01Ups / 2);
  const sideBUps = Math.floor(ps01Ups / 2);
  const totalSlitWidth = jumboWidths.reduce((a, b) => a + b, 0);
  const trimMm = motherDeckle - totalSlitWidth;
  const density = 0.91;
  const dateStr = new Date().toISOString();
  const displayDate = new Date().toLocaleDateString('en-GB');

  // Authoritative weight calculation per item
  const items: PlanItem[] = [];
  let currentSideAArm = 1;
  let currentSideBArm = 9;
  let totalPlannedQuantityKg = 0;

  const planId = `ps01-plan-${Date.now()}-${planIndex + 1}`;
  const widthSummary = jumboWidths.length <= 2 
    ? jumboWidths.join('+') + 'MM' 
    : `${jumboWidths[0]}+${jumboWidths[1]}+${jumboWidths[2]}${jumboWidths[3] ? '+' + jumboWidths[3] : ''}MM`;
  const planNumber = `PS01-JP${planIndex + 1}-${film}-${widthSummary}`;
  const segmentId = `seg-ps01-${planIndex + 1}-1`;

  const uniqueWidths = Array.from(new Set(jumboWidths));

  for (let i = 0; i < ps01Ups; i++) {
    const width = jumboWidths[i];
    const isSideA = i % 2 === 0 ? (currentSideAArm <= sideAUps) : (currentSideBArm > 8 + sideBUps);
    const station: 'SIDE_A' | 'SIDE_B' = isSideA ? 'SIDE_A' : 'SIDE_B';
    const physicalArm = station === 'SIDE_A' ? currentSideAArm++ : currentSideBArm++;
    const posIndex = i + 1;

    const singleReelWeightKg = Number(((width * lengthM * thickness * density) / 1000000).toFixed(2));
    const itemTotalWeightKg = Number((singleReelWeightKg * repetitions).toFixed(2));
    totalPlannedQuantityKg += itemTotalWeightKg;

    const matchedReq = associatedReqs.find(r => r.required_jumbo_width_mm === width) || associatedReqs[0];
    const formatWidthsMultiplier = (widths: number[]): string => {
      if (!widths || widths.length === 0) return '';
      const counts = new Map<number, number>();
      for (const w of widths) {
        counts.set(w, (counts.get(w) || 0) + 1);
      }
      return Array.from(counts.entries())
        .map(([w, count]) => (count > 1 ? `${w}*${count}` : `${w}`))
        .join(' + ');
    };
    const customerLabel = matchedReq 
      ? `MSL ${matchedReq.ups}-UPS: ${formatWidthsMultiplier(matchedReq.finished_widths_covered || [])}`
      : `${width}mm JUMBO`;

    const uniqueIndex = uniqueWidths.indexOf(width);
    const sizeItemNumber = (uniqueIndex + 1) * 10;

    items.push({
      id: `item-${planId}-${posIndex}`,
      plan_id: planId,
      segment_id: segmentId,
      position: physicalArm,
      positions: [physicalArm],
      position_label: `Pos ${posIndex} (Arm ${physicalArm})`,
      station: station,
      sales_order: `JR-${film}-${width}`,
      item_number: sizeItemNumber,
      customer: customerLabel,
      film: film,
      width_mm: width,
      length_m: lengthM,
      core: 6,
      treatment_side: 'OS',
      reels: repetitions,
      ups: 1,
      initial_ups: 1,
      deckle_mm: width,
      weight_per_pack_kg: singleReelWeightKg,
      total_weight_kg: itemTotalWeightKg,
      is_closed: true,
    });
  }

  totalPlannedQuantityKg = Number(totalPlannedQuantityKg.toFixed(2));
  const singleMillRollWeightKg = Number(((motherDeckle * lengthM * thickness * density) / 1000000).toFixed(2));
  const singleTrimWeightKg = Number(((trimMm * lengthM * thickness * density) / 1000000).toFixed(2));
  const millRollWeightKg = Number((singleMillRollWeightKg * repetitions).toFixed(2));
  const trimWeightKg = Number((singleTrimWeightKg * repetitions).toFixed(2));
  const wastePercent = Number(((trimMm / motherDeckle) * 100).toFixed(2));

  const segment: PlanSegment = {
    id: segmentId,
    plan_id: planId,
    segment_number: 1,
    name: `Jumbo Slit Layout (${ps01Ups}-UPS on 10,400mm Mother Deckle)`,
    start_pack: 1,
    end_pack: repetitions,
    repetitions: repetitions,
    total_slit_width_mm: totalSlitWidth,
    trim_mm: trimMm,
    ups: ps01Ups,
    items: items,
  };

  const isRelaxed = trimMm > 280 && trimMm <= 500;

  return {
    id: planId,
    planning_run_id: `run-jumbo-${film}`,
    plan_number: planNumber,
    machine_id: 'PS01',
    machine_name: 'PRIMARY SLITTER 1 (PS01)',
    film: film,
    thickness_micron: thickness,
    density: density,
    deckle_mm: motherDeckle,
    total_slit_width_mm: totalSlitWidth,
    trim_mm: trimMm,
    allowed_trim_mm: 280,
    remaining_web_mm: 0,
    ups: ps01Ups,
    max_ups_capacity: 16,
    repetitions: repetitions,
    length_m: lengthM,
    planned_mr_length_m: lengthM,
    mill_roll_weight_kg: millRollWeightKg,
    trim_weight_kg: trimWeightKg,
    waste_percent: wastePercent,
    planned_quantity_kg: totalPlannedQuantityKg,
    order_weight_kg: totalPlannedQuantityKg,
    total_reels: ps01Ups * repetitions,
    weight_per_pack_total_kg: Number((totalPlannedQuantityKg / repetitions).toFixed(2)),
    rejection_material: `R-${film}`,
    trim_rule_mode: isRelaxed ? 'RELAXED_50MM' : 'NORMAL',
    min_trim_mm_used: isRelaxed ? 281 : 150,
    max_trim_mm_used: isRelaxed ? 500 : 280,
    duplex_layout: {
      side_a_ups: sideAUps,
      side_b_ups: sideBUps,
      is_dual_core: false,
      is_dual_length: false,
      balance_delta: Math.abs(sideAUps - sideBUps),
    },
    doc_ref: 'APS/QR/PL/01',
    rev_no: 0,
    issue_date: displayDate,
    items: items,
    changes: [],
    segments: [segment],
    status: 'APPROVED',
    approved_by: createdBy,
    approved_at: dateStr,
    created_at: dateStr,
  };
}

/**
 * Generate a separate, authoritative PS01 SlitterPlan for a complete Mother Roll Deckle Run Group.
 * This accurately calculates:
 * 1. The exact Number of Mother Roll Packs (Sets / Repetitions) required to satisfy all physical rolls.
 * 2. The proper length (m) of the Jumbo Mother Rolls.
 * 3. Accurate Knife cut allocations to each downstream Metallizer (MSL) Plan.
 */
export interface WidthWiseReconciliationResult {
  is_valid: boolean;
  errors: string[];
  widthDetails: {
    width_mm: number;
    manufactured_count: number;
    consumed_count: number;
    difference: number;
  }[];
}

/**
 * Generic Width-Wise Jumbo Quantity Reconciliation Validator.
 * For EACH jumbo width W independently:
 * PS manufactured rolls of width W MUST EQUAL downstream MSL consumed/mounted rolls of width W.
 * Zero unallocated manufactured rolls. Zero downstream consumption of unmanufactured rolls.
 */
export function validateWidthWiseJumboReconciliation(
  manufacturedJumbos: { width_mm: number; count?: number }[] | number[],
  consumedJumbos: { width_mm?: number; required_jumbo_width_mm?: number; count?: number; required_rolls_count?: number }[]
): WidthWiseReconciliationResult {
  const mfgCounts = new Map<number, number>();
  const consumedCounts = new Map<number, number>();

  if (Array.isArray(manufacturedJumbos)) {
    for (const item of manufacturedJumbos) {
      if (typeof item === 'number') {
        mfgCounts.set(item, (mfgCounts.get(item) || 0) + 1);
      } else if (item && typeof item === 'object') {
        const w = item.width_mm;
        const c = item.count ?? 1;
        mfgCounts.set(w, (mfgCounts.get(w) || 0) + c);
      }
    }
  }

  if (Array.isArray(consumedJumbos)) {
    for (const item of consumedJumbos) {
      if (item && typeof item === 'object') {
        const w = item.required_jumbo_width_mm ?? item.width_mm;
        const c = item.required_rolls_count ?? item.count ?? 1;
        if (typeof w === 'number') {
          consumedCounts.set(w, (consumedCounts.get(w) || 0) + c);
        }
      }
    }
  }

  const allWidths = Array.from(new Set([...mfgCounts.keys(), ...consumedCounts.keys()])).sort((a, b) => a - b);
  const errors: string[] = [];
  const widthDetails = allWidths.map(w => {
    const mfg = mfgCounts.get(w) || 0;
    const con = consumedCounts.get(w) || 0;
    const diff = mfg - con;
    if (diff !== 0) {
      if (diff > 0) {
        errors.push(`Width ${w}mm: Manufactured ${mfg} rolls, but MSL only consumes ${con} rolls (${diff} unallocated rolls).`);
      } else {
        errors.push(`Width ${w}mm: MSL consumes ${con} rolls, but PS01 only manufactures ${mfg} rolls (missing ${-diff} rolls).`);
      }
    }
    return {
      width_mm: w,
      manufactured_count: mfg,
      consumed_count: con,
      difference: diff,
    };
  });

  return {
    is_valid: errors.length === 0,
    errors,
    widthDetails,
  };
}

/**
 * Generate a separate, authoritative PS01 SlitterPlan for a complete Mother Roll Deckle Run Group.
 * This accurately calculates:
 * 1. The exact Number of Mother Roll Packs (Sets / Repetitions) required to satisfy all physical rolls.
 * 2. The proper length (m) of the Jumbo Mother Rolls.
 * 3. Accurate Knife cut allocations to each downstream Metallizer (MSL) Plan.
 */
export function generatePS01PlanForDeckleGroup(
  reqs: JumboRequirement[],
  runIndex: number,
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): SlitterPlan {
  if (!reqs || reqs.length === 0) {
    throw new Error('No requirements provided for mother run group');
  }

  const primaryReq = reqs[0];
  const feasibility = primaryReq.ps01_feasibility;
  let cutCombination = feasibility?.ps01_cut_combination && feasibility.ps01_cut_combination.length > 0
    ? [...feasibility.ps01_cut_combination]
    : (primaryReq.ps01_cut_combination && primaryReq.ps01_cut_combination.length > 0
        ? [...primaryReq.ps01_cut_combination]
        : Array(feasibility?.ps01_ups || (primaryReq.required_jumbo_width_mm <= 2600 ? 4 : 3)).fill(primaryReq.required_jumbo_width_mm));

  // If all requirements in this deckle group have the same width W, enforce cutCombination is pure W:
  const allSameWidth = reqs.every(r => r.required_jumbo_width_mm === primaryReq.required_jumbo_width_mm);
  const isPureDeckle = cutCombination.every(w => w === cutCombination[0]);

  if (allSameWidth && (isPureDeckle || cutCombination.length === 3 || cutCombination.length === 4)) {
    cutCombination = Array(cutCombination.length).fill(primaryReq.required_jumbo_width_mm);
  }

  // Count how many times each jumbo width appears in this mother deckle pattern
  const patternWidthCounts = new Map<number, number>();
  cutCombination.forEach(w => patternWidthCounts.set(w, (patternWidthCounts.get(w) || 0) + 1));

  // Calculate repetitions (number of PS01 Mother Roll packs/sets needed)
  // For each unique width W in cutCombination, sets needed = ceil(total_demand_for_W / slots_of_W_in_pattern)
  let setsNeeded = 1;
  for (const [w, slotsInPattern] of patternWidthCounts.entries()) {
    const totalRollsNeededForWidth = reqs
      .filter(r => r.required_jumbo_width_mm === w)
      .reduce((sum, r) => sum + (r.required_rolls_count || 1), 0);
    const setsForWidth = Math.max(1, Math.ceil(totalRollsNeededForWidth / slotsInPattern));
    if (setsForWidth > setsNeeded) {
      setsNeeded = setsForWidth;
    }
  }

  // Map each cut position to the specific MSL requirement that utilizes this jumbo width
  const associatedReqs: JumboRequirement[] = [];
  const assignedCountsPerReq = new Map<string, number>();

  for (let i = 0; i < cutCombination.length; i++) {
    const cutWidth = cutCombination[i];
    // Find matching req with exact width or closest width
    const matchingReqs = reqs.filter(r => r.required_jumbo_width_mm === cutWidth);
    let assignedReq = matchingReqs[0] || primaryReq;

    if (matchingReqs.length > 1) {
      // Pick the requirement that still needs more slots in the pattern (unmet slot quota)
      matchingReqs.sort((a, b) => {
        const quotaA = Math.ceil((a.required_rolls_count || 1) / setsNeeded);
        const quotaB = Math.ceil((b.required_rolls_count || 1) / setsNeeded);
        const assignedA = assignedCountsPerReq.get(a.id) || 0;
        const assignedB = assignedCountsPerReq.get(b.id) || 0;
        return (quotaB - assignedB) - (quotaA - assignedA);
      });
      assignedReq = matchingReqs[0];
    }

    associatedReqs.push(assignedReq);
    assignedCountsPerReq.set(assignedReq.id, (assignedCountsPerReq.get(assignedReq.id) || 0) + 1);
  }

  const lengthM = Math.max(...reqs.map(r => r.required_jumbo_length_m || 20000));
  const thickness = primaryReq.thickness_micron || 18;

  const plan = generatePS01PlanForJumboCombination(
    cutCombination,
    runIndex - 1,
    film,
    lengthM,
    thickness,
    associatedReqs,
    createdBy,
    setsNeeded
  );

  // Hard width-wise quantity reconciliation guard
  const mfgRolls: { width_mm: number; count: number }[] = [];
  for (const [w, countInPattern] of patternWidthCounts.entries()) {
    mfgRolls.push({ width_mm: w, count: countInPattern * setsNeeded });
  }
  const reconciliation = validateWidthWiseJumboReconciliation(mfgRolls, reqs);
  if (!reconciliation.is_valid) {
    throw new Error(
      `PS01 Width-Wise Quantity Reconciliation Guard Violation: Deckle run #${runIndex} (${film}) reconciliation failed:\n${reconciliation.errors.join('\n')}`
    );
  }

  return plan;
}

/**
 * Generate a separate, authoritative PS01 SlitterPlan for an INDIVIDUAL Jumbo Roll Plan.
 * STRICT REQUIREMENT: Each Jumbo Plan has its own isolated Factory Sheet with NO cross-plan data mixing.
 */
export function generatePS01PlanForSingleJumbo(
  req: JumboRequirement,
  planIndex: number,
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): SlitterPlan {
  const feasibilityCuts = req.ps01_feasibility?.ps01_cut_combination || req.ps01_cut_combination;
  let widths = feasibilityCuts && feasibilityCuts.length > 0
    ? [...feasibilityCuts]
    : Array(req.ps01_feasibility?.ps01_ups || (req.required_jumbo_width_mm <= 2600 ? 4 : 3)).fill(req.required_jumbo_width_mm);

  // If pure pattern or single jumbo requirement representing pure cuts:
  const isPurePattern = widths.every(w => w === widths[0]) || (req.is_master_width_clustered && widths.every(w => Math.abs(w - req.required_jumbo_width_mm) <= 30));
  if (isPurePattern) {
    widths = Array(widths.length).fill(req.required_jumbo_width_mm);
  }

  const matchingWidthCount = widths.filter(w => w === req.required_jumbo_width_mm).length;
  // Defensive protection: For a genuine single-requirement pure PS pattern,
  // calculate usageInPattern from the actual number of cut positions occupied by that requirement (widths.length).
  const upsInPattern = isPurePattern ? widths.length : Math.max(1, matchingWidthCount);
  const setsNeeded = Math.max(1, Math.ceil((req.required_rolls_count || 1) / upsInPattern));

  const plan = generatePS01PlanForJumboCombination(
    widths,
    planIndex,
    film,
    req.required_jumbo_length_m,
    req.thickness_micron || 18,
    Array(widths.length).fill(req),
    createdBy,
    setsNeeded
  );

  // Hard width-wise quantity reconciliation guard
  const patternWidthCounts = new Map<number, number>();
  widths.forEach(w => patternWidthCounts.set(w, (patternWidthCounts.get(w) || 0) + 1));
  const mfgRolls: { width_mm: number; count: number }[] = [];
  for (const [w, countInPattern] of patternWidthCounts.entries()) {
    mfgRolls.push({ width_mm: w, count: countInPattern * setsNeeded });
  }
  const reconciliation = validateWidthWiseJumboReconciliation(mfgRolls, [req]);
  if (!reconciliation.is_valid) {
    throw new Error(
      `PS01 Width-Wise Quantity Reconciliation Guard Violation: Single-jumbo plan #${planIndex + 1} (${film}) reconciliation failed:\n${reconciliation.errors.join('\n')}`
    );
  }

  return plan;
}

/**
 * Generate a customer-standard SlitterPlan for a Metallizer Slitter (MSL) Plan.
 * This formats the MSL slitting job in the standard BOPP factory sheet layout (PlanDetailViewer),
 * with duplex arms, knife positions, customer sales orders, roll repetitions (packs),
 * jumbo mount width, trim waste, and quality checks.
 */
export function generateMSLSlitterPlan(
  req: JumboRequirement,
  planIndex: number,
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): SlitterPlan {
  const mountJumboWidth = req.required_jumbo_width_mm;
  const finishedCuts = req.finished_widths_covered || [];
  const mslUps = finishedCuts.length || req.ups || 1;
  const sideAUps = Math.ceil(mslUps / 2);
  const sideBUps = Math.floor(mslUps / 2);
  const totalSlitWidth = finishedCuts.reduce((a, b) => a + b, 0);
  const trimMm = req.expected_trim_mm !== undefined ? req.expected_trim_mm : Math.max(0, mountJumboWidth - totalSlitWidth);
  const density = 0.91;
  const jumboLengthM = req.required_jumbo_length_m || 20000;
  const thickness = req.thickness_micron || 18;
  const jumboRollsCount = req.required_rolls_count || 1;
  const dateStr = new Date().toISOString();
  const displayDate = new Date().toLocaleDateString('en-GB');

  // Derive exact Reel / Pack Length from covered orders (e.g. 18,700m or 20,000m or 9,350m)
  const ordersCovered = req.orders_covered || [];
  const coveredLengths = ordersCovered.map(o => o.length_m).filter(Boolean);
  const packLengthM = coveredLengths.length > 0 
    ? Math.max(...coveredLengths) 
    : Math.round(jumboLengthM / Math.max(1, req.package_multiple || 1));
  const setsPerJumbo = Math.max(1, Math.round(jumboLengthM / packLengthM));
  const totalPacks = jumboRollsCount * setsPerJumbo;

  const planId = `msl-slitter-plan-${req.id || planIndex + 1}`;
  const widthSummary = finishedCuts.length <= 3 
    ? finishedCuts.join('+') + 'MM' 
    : `${finishedCuts.slice(0, 3).join('+')}+${finishedCuts.length - 3}MORE`;
  const planNumber = `MSL-P${planIndex + 1}-${film}-${mountJumboWidth}MM-(${widthSummary})`;
  const segmentId = `seg-msl-${planIndex + 1}-1`;

  // 1. Determine unique lengths from covered orders
  const uniqueLengths = Array.from(new Set(coveredLengths)).sort((a, b) => b - a);

  // 2. Assign Station (SIDE A vs SIDE B) and physical duplex arms (1..8 on A, 9..16 on B)
  // CRITICAL DUPLEX RULE: A rewind shaft CANNOT mix different roll lengths!
  // All rolls on Side A shaft MUST wind length L_A. All rolls on Side B shaft MUST wind length L_B.
  interface KnifeArm {
    posIndex: number;
    cutWidth: number;
    station: 'SIDE_A' | 'SIDE_B';
    physicalArm: number;
    assignedLengthM: number;
    capacityReels: number;
    reelsPerPack: number;
  }

  const knifeArms: KnifeArm[] = [];
  let currentSideAArm = 1;
  let currentSideBArm = 9;

  if (uniqueLengths.length > 1) {
    const longLen = uniqueLengths[0];
    const shortLen = uniqueLengths[1];

    const longReelsReq = ordersCovered.filter(o => o.length_m === longLen).reduce((s, o) => s + o.required_reels, 0);
    const reelsPerPackLong = Math.max(1, Math.round(packLengthM / longLen));
    const reelsPerPackShort = Math.max(1, Math.round(packLengthM / shortLen));

    const cutsNeededLong = Math.round(longReelsReq / (totalPacks * reelsPerPackLong)) || 1;

    const longOrders = ordersCovered.filter(o => o.length_m === longLen);
    const longWidths = new Set(longOrders.map(o => o.width_mm));

    const sortedCuts = [...finishedCuts].map((w, idx) => ({ w, idx }));
    sortedCuts.sort((a, b) => {
      const aIsLong = longWidths.has(a.w) ? 1 : 0;
      const bIsLong = longWidths.has(b.w) ? 1 : 0;
      return bIsLong - aIsLong;
    });

    sortedCuts.forEach((sc, i) => {
      const isSideA = i < cutsNeededLong;
      const station: 'SIDE_A' | 'SIDE_B' = isSideA ? 'SIDE_A' : 'SIDE_B';
      const physicalArm = isSideA ? currentSideAArm++ : currentSideBArm++;
      const assignedLengthM = isSideA ? longLen : shortLen;
      const reelsPerPack = isSideA ? reelsPerPackLong : reelsPerPackShort;
      knifeArms.push({
        posIndex: sc.idx + 1,
        cutWidth: sc.w,
        station,
        physicalArm,
        assignedLengthM,
        capacityReels: totalPacks * reelsPerPack,
        reelsPerPack,
      });
    });
  } else {
    const commonLengthM = uniqueLengths[0] || packLengthM;
    const reelsPerPack = Math.max(1, Math.round(packLengthM / commonLengthM));
    finishedCuts.forEach((w, i) => {
      const isSideA = i % 2 === 0;
      const station: 'SIDE_A' | 'SIDE_B' = isSideA ? 'SIDE_A' : 'SIDE_B';
      const physicalArm = isSideA ? currentSideAArm++ : currentSideBArm++;
      knifeArms.push({
        posIndex: i + 1,
        cutWidth: w,
        station,
        physicalArm,
        assignedLengthM: commonLengthM,
        capacityReels: totalPacks * reelsPerPack,
        reelsPerPack,
      });
    });
  }

  knifeArms.sort((a, b) => a.posIndex - b.posIndex);

  // 3. Assign ordersCovered to knifeArms strictly according to required_reels and weight_kg!
  const items: PlanItem[] = [];
  const changes: PlanChange[] = [];
  let totalPlannedQuantityKg = 0;

  const orderRemaining = ordersCovered.map(o => ({
    ...o,
    reelsLeft: o.required_reels,
    weightLeft: o.weight_kg,
  }));

  for (const arm of knifeArms) {
    let armCapacityLeft = arm.capacityReels;
    let packOffset = 0;

    const matching = orderRemaining.filter(o => o.width_mm === arm.cutWidth && o.length_m === arm.assignedLengthM && o.reelsLeft > 0);
    const candidateOrders = matching.length > 0 
      ? matching 
      : orderRemaining.filter(o => o.width_mm === arm.cutWidth && o.reelsLeft > 0);

    for (const ord of candidateOrders) {
      if (armCapacityLeft <= 0) break;
      const reelsToTake = Math.min(armCapacityLeft, ord.reelsLeft);
      if (reelsToTake <= 0) continue;

      const singleReelWeightKg = Number(((arm.cutWidth * arm.assignedLengthM * thickness * density) / 1000000).toFixed(2));
      const allocatedWeightKg = ord.reelsLeft === reelsToTake 
        ? ord.weightLeft 
        : Number((singleReelWeightKg * reelsToTake).toFixed(2));

      ord.reelsLeft -= reelsToTake;
      ord.weightLeft = Math.max(0, Number((ord.weightLeft - allocatedWeightKg).toFixed(2)));
      armCapacityLeft -= reelsToTake;

      const activePacks = Math.ceil(reelsToTake / arm.reelsPerPack);
      const startPack = packOffset + 1;
      packOffset += activePacks;
      const isFuture = startPack > 1;

      totalPlannedQuantityKg += allocatedWeightKg;

      items.push({
        id: `item-${planId}-${arm.posIndex}-${ord.sales_order}-${ord.item_number}`,
        plan_id: planId,
        segment_id: segmentId,
        position: arm.physicalArm,
        positions: [arm.physicalArm],
        position_label: `Pos ${arm.posIndex} (Arm ${arm.physicalArm})`,
        station: arm.station,
        sales_order: ord.sales_order.startsWith('SO#') ? ord.sales_order : `SO#${ord.sales_order}`,
        item_number: ord.item_number,
        customer: ord.customer,
        film: film,
        width_mm: arm.cutWidth,
        length_m: arm.assignedLengthM,
        core: 6,
        treatment_side: 'OS',
        reels: reelsToTake,
        ups: isFuture ? 0 : 1,
        initial_ups: isFuture ? 0 : 1,
        start_pack: startPack,
        active_packs: activePacks,
        deckle_mm: arm.cutWidth,
        weight_per_pack_kg: Number((singleReelWeightKg * arm.reelsPerPack).toFixed(2)),
        total_weight_kg: allocatedWeightKg,
        is_closed: true,
        is_future_replacement: isFuture,
        replacement_instruction: isFuture ? `Starts on Arm ${arm.physicalArm} after Pack ${startPack - 1}` : undefined,
      });

      if (isFuture) {
        changes.push({
          id: `change-${planId}-${arm.posIndex}-${startPack - 1}`,
          plan_id: planId,
          segment_id: segmentId,
          position: arm.physicalArm,
          old_width_mm: arm.cutWidth,
          new_width_mm: arm.cutWidth,
          after_pack: startPack - 1,
          reason: 'ORDER_COMPLETED',
          instruction: `After Pack ${startPack - 1}: Reassign Arm ${arm.physicalArm} (${arm.cutWidth}mm) to ${ord.customer} (${ord.sales_order})`,
          old_order_ref: `Arm ${arm.physicalArm}`,
          new_order_ref: `${ord.sales_order}-${ord.item_number}`,
          created_at: dateStr,
        });
      }
    }

    if (armCapacityLeft > 0) {
      const singleReelWeightKg = Number(((arm.cutWidth * arm.assignedLengthM * thickness * density) / 1000000).toFixed(2));
      const bufferWeightKg = Number((singleReelWeightKg * armCapacityLeft).toFixed(2));
      totalPlannedQuantityKg += bufferWeightKg;
      const isFuture = (packOffset + 1) > 1;

      items.push({
        id: `item-${planId}-${arm.posIndex}-BUFFER`,
        plan_id: planId,
        segment_id: segmentId,
        position: arm.physicalArm,
        positions: [arm.physicalArm],
        position_label: `Pos ${arm.posIndex} (Arm ${arm.physicalArm})`,
        station: arm.station,
        sales_order: 'BUFFER',
        item_number: arm.posIndex * 10,
        customer: 'PLANNEX BUFFER',
        film: film,
        width_mm: arm.cutWidth,
        length_m: arm.assignedLengthM,
        core: 6,
        treatment_side: 'OS',
        reels: armCapacityLeft,
        ups: isFuture ? 0 : 1,
        initial_ups: isFuture ? 0 : 1,
        start_pack: packOffset + 1,
        active_packs: Math.ceil(armCapacityLeft / arm.reelsPerPack),
        deckle_mm: arm.cutWidth,
        weight_per_pack_kg: Number((singleReelWeightKg * arm.reelsPerPack).toFixed(2)),
        total_weight_kg: bufferWeightKg,
        is_closed: false,
        is_future_replacement: isFuture,
      });
    }
  }

  items.sort((a, b) => {
    const numA = parseInt(a.position_label?.match(/\d+/)?.[0] || '0', 10);
    const numB = parseInt(b.position_label?.match(/\d+/)?.[0] || '0', 10);
    if (numA !== numB) return numA - numB;
    return (a.start_pack || 1) - (b.start_pack || 1);
  });

  totalPlannedQuantityKg = Number(totalPlannedQuantityKg.toFixed(2));
  const singlePackMillRollWeightKg = Number(((mountJumboWidth * packLengthM * thickness * density) / 1000000).toFixed(2));
  const singlePackTrimWeightKg = Number(((trimMm * packLengthM * thickness * density) / 1000000).toFixed(2));
  const millRollWeightKg = Number((singlePackMillRollWeightKg * totalPacks).toFixed(2));
  const trimWeightKg = Number((singlePackTrimWeightKg * totalPacks).toFixed(2));
  const wastePercent = Number(((trimMm / mountJumboWidth) * 100).toFixed(2));
  const totalReelsCount = items.reduce((sum, item) => sum + item.reels, 0);

  const segment: PlanSegment = {
    id: segmentId,
    plan_id: planId,
    segment_number: 1,
    name: `MSL Finished Slit Pattern (${mslUps}-UPS on ${mountJumboWidth}mm Jumbo Mount)`,
    start_pack: 1,
    end_pack: totalPacks,
    repetitions: totalPacks,
    total_slit_width_mm: totalSlitWidth,
    trim_mm: trimMm,
    ups: mslUps,
    items: items,
  };

  const sideAItems = items.filter(it => it.station === 'SIDE_A');
  const sideBItems = items.filter(it => it.station === 'SIDE_B');
  const actualSideAUps = new Set(sideAItems.map(it => it.position)).size;
  const actualSideBUps = new Set(sideBItems.map(it => it.position)).size;
  const sideALen = sideAItems[0]?.length_m || packLengthM;
  const sideBLen = sideBItems[0]?.length_m || packLengthM;
  const isDualLen = sideAItems.some(it => it.length_m !== sideALen) || sideBItems.some(it => it.length_m !== sideBLen) || (sideALen !== sideBLen);

  return {
    id: planId,
    planning_run_id: `run-msl-${film}`,
    plan_number: planNumber,
    machine_id: 'MSL',
    machine_name: 'METALLIZER SLITTER (MSL)',
    film: film,
    thickness_micron: thickness,
    density: density,
    deckle_mm: mountJumboWidth,
    total_slit_width_mm: totalSlitWidth,
    trim_mm: trimMm,
    allowed_trim_mm: 50,
    remaining_web_mm: 0,
    ups: mslUps,
    max_ups_capacity: 16,
    repetitions: totalPacks,
    length_m: packLengthM,
    planned_mr_length_m: packLengthM,
    mill_roll_weight_kg: millRollWeightKg,
    trim_weight_kg: trimWeightKg,
    waste_percent: wastePercent,
    planned_quantity_kg: totalPlannedQuantityKg,
    order_weight_kg: totalPlannedQuantityKg,
    total_reels: totalReelsCount,
    weight_per_pack_total_kg: Number((totalPlannedQuantityKg / totalPacks).toFixed(2)),
    rejection_material: `R-${film}`,
    trim_rule_mode: 'NORMAL',
    min_trim_mm_used: 10,
    max_trim_mm_used: 50,
    duplex_layout: {
      side_a_ups: actualSideAUps,
      side_b_ups: actualSideBUps,
      is_dual_core: false,
      is_dual_length: isDualLen,
      side_a_length_m: sideALen,
      side_b_length_m: sideBLen,
      balance_delta: Math.abs(actualSideAUps - actualSideBUps),
    },
    doc_ref: 'APS/QR/MSL/01',
    rev_no: 0,
    issue_date: displayDate,
    items: items,
    changes: changes,
    segments: [segment],
    status: 'APPROVED',
    approved_by: createdBy,
    approved_at: dateStr,
    created_at: dateStr,
    notes: `Mount Jumbo: ${mountJumboWidth} mm | Pack Length: ${packLengthM.toLocaleString()} m | Total Packs: ${totalPacks} Packs (${jumboRollsCount} Jumbo Roll${jumboRollsCount > 1 ? 's' : ''} × ${setsPerJumbo} Sets) | Upstream PS01 Origin: ${req.ps01_parent_deckle_id || 'PS01 Mother Run'}`,
  };
}

/**
 * Generate optimal PS01 Manufacturing Slitter Plans for approved Jumbo Requirements.
 * CRITICAL OPTIMIZATION RULES:
 * 1. Minimizes unnecessary jumbo-roll manufacturing and maximizes usable jumbo length.
 * 2. Allows different jumbo widths in the same 3-UPS or 4-UPS PS01 pattern (e.g. 3385 + 3425 + 3385 mm).
 * 3. 3-UPS is preferred; 4-UPS is maximum; 5/6-UPS are strictly forbidden.
 * 4. Intelligently consolidates similar jumbo widths (within 15mm) to reduce PS01 knife setups.
 * 5. Guarantees every individual jumbo-roll manufacturing plan maintains its own separate Factory Sheet.
 */
export function generatePS01ManufacturingPlansForJumbos(
  requirements: JumboRequirement[],
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): {
  plans: SlitterPlan[];
  film: string;
  logs: any[];
} {
  if (requirements.length === 0) {
    return { plans: [], film, logs: [] };
  }

  const motherDeckle = DEFAULT_PLANNING_RULES.deckle_width_mm || 10400;
  const thickness = requirements[0]?.thickness_micron || 18;

  // Represent roll requirements as distinct demand buckets with remaining roll counts
  interface JumboDemandBucket {
    id: string;
    req: JumboRequirement;
    width: number;
    length: number;
    remainingRolls: number;
  }

  const buckets: JumboDemandBucket[] = requirements.map((req, idx) => ({
    id: req.id || `req-${idx}`,
    req,
    width: req.required_jumbo_width_mm,
    length: req.required_jumbo_length_m,
    remainingRolls: req.required_rolls_count || 1,
  }));

  const logs: any[] = [];

  // Intelligent MSL-trim-safe consolidation of similar jumbo widths (within 15 mm)
  // CRITICAL: Any unification of jumbo widths between two requirements must satisfy:
  // W_unified - sum(cuts_A) in [18, 45] AND W_unified - sum(cuts_B) in [18, 45]
  for (let i = 0; i < buckets.length; i++) {
    for (let j = i + 1; j < buckets.length; j++) {
      if (buckets[i].length !== buckets[j].length) continue;
      const cutsA = buckets[i].req.finished_widths_covered || [];
      const cutsB = buckets[j].req.finished_widths_covered || [];
      const sumA = cutsA.reduce((a, b) => a + b, 0);
      const sumB = cutsB.reduce((a, b) => a + b, 0);

      const minSafeW = Math.max(sumA + 18, sumB + 18);
      const maxSafeW = Math.min(sumA + 45, sumB + 45);

      if (minSafeW <= maxSafeW) {
        const avg = Math.round((buckets[i].width + buckets[j].width) / 2);
        const candidateW = Math.max(minSafeW, Math.min(maxSafeW, avg));
        const evalResult = evaluatePS01CombinationFeasibility([candidateW, candidateW, candidateW], film, thickness);
        if (evalResult.is_feasible && evalResult.status !== 'RED') {
          const originalI = buckets[i].width;
          const originalJ = buckets[j].width;
          buckets[i].width = candidateW;
          buckets[j].width = candidateW;
          logs.push({
            step: logs.length + 1,
            message: `Consolidated similar jumbo widths (${originalI}mm & ${originalJ}mm) to MSL-safe common width ${candidateW}mm.`,
            type: 'INFO',
          });
        }
      }
    }
  }

  const plans: SlitterPlan[] = [];
  let planIndex = 0;

  // Fast combinatorial search on distinct buckets
  let activeBuckets = buckets.filter(b => b.remainingRolls > 0);

  while (activeBuckets.length > 0) {
    let bestCombo: {
      b1: JumboDemandBucket;
      b2: JumboDemandBucket;
      b3: JumboDemandBucket;
      b4?: JumboDemandBucket;
      widths: number[];
      ups: number;
      trim: number;
      status: 'GREEN' | 'YELLOW';
      score: number;
      i: number;
      j: number;
      k: number;
      l?: number;
    } | null = null;

    // 1. Check 3-UPS across distinct buckets (Priority 1) - enforce length compatibility
    const bLen = activeBuckets.length;
    for (let i = 0; i < bLen; i++) {
      const b1 = activeBuckets[i];
      for (let j = i; j < bLen; j++) {
        const b2 = activeBuckets[j];
        if (b2.length !== b1.length) continue;
        for (let k = j; k < bLen; k++) {
          const b3 = activeBuckets[k];
          if (b3.length !== b1.length) continue;

          // Check if sufficient rolls exist for this combination
          let canForm = false;
          if (i === j && j === k) {
            canForm = b1.remainingRolls >= 3;
          } else if (i === j) {
            canForm = b1.remainingRolls >= 2 && b3.remainingRolls >= 1;
          } else if (j === k) {
            canForm = b1.remainingRolls >= 1 && b2.remainingRolls >= 2;
          } else {
            canForm = b1.remainingRolls >= 1 && b2.remainingRolls >= 1 && b3.remainingRolls >= 1;
          }

          if (!canForm) continue;

          const widths = [b1.width, b2.width, b3.width];
          const evalResult = evaluatePS01CombinationFeasibility(widths, film, thickness);

          if (evalResult.is_feasible && evalResult.status !== 'RED') {
            let score = 20000;
            if (evalResult.status === 'GREEN') score += 5000;
            score -= Math.abs(evalResult.ps01_trim_mm - 190);
            if (b1.width === b2.width && b2.width === b3.width) score += 2000;
            else if (b1.width === b2.width || b2.width === b3.width || b1.width === b3.width) score += 1000;

            if (!bestCombo || score > bestCombo.score) {
              bestCombo = {
                b1,
                b2,
                b3,
                widths,
                ups: 3,
                trim: evalResult.ps01_trim_mm,
                status: evalResult.status,
                score,
                i,
                j,
                k,
              };
            }
          }
        }
      }
    }

    // 2. If no 3-UPS found, try 4-UPS across distinct buckets (Priority 2) - enforce length compatibility
    if (!bestCombo) {
      for (let i = 0; i < bLen; i++) {
        const b1 = activeBuckets[i];
        for (let j = i; j < bLen; j++) {
          const b2 = activeBuckets[j];
          if (b2.length !== b1.length) continue;
          for (let k = j; k < bLen; k++) {
            const b3 = activeBuckets[k];
            if (b3.length !== b1.length) continue;
            for (let l = k; l < bLen; l++) {
              const b4 = activeBuckets[l];
              if (b4.length !== b1.length) continue;

              // Count usage per bucket index
              const counts: Record<number, number> = {};
              counts[i] = (counts[i] || 0) + 1;
              counts[j] = (counts[j] || 0) + 1;
              counts[k] = (counts[k] || 0) + 1;
              counts[l] = (counts[l] || 0) + 1;

              const canForm = Object.entries(counts).every(([idx, needed]) => activeBuckets[Number(idx)].remainingRolls >= needed);
              if (!canForm) continue;

              const widths = [b1.width, b2.width, b3.width, b4.width];
              const evalResult = evaluatePS01CombinationFeasibility(widths, film, thickness);

              if (evalResult.is_feasible && evalResult.status !== 'RED') {
                let score = 10000;
                if (evalResult.status === 'GREEN') score += 3000;
                score -= Math.abs(evalResult.ps01_trim_mm - 190);

                if (!bestCombo || score > bestCombo.score) {
                  bestCombo = {
                    b1,
                    b2,
                    b3,
                    b4,
                    widths,
                    ups: 4,
                    trim: evalResult.ps01_trim_mm,
                    status: evalResult.status,
                    score,
                    i,
                    j,
                    k,
                    l,
                  };
                }
              }
            }
          }
        }
      }
    }

    // 3. Batch apply the best combo
    if (bestCombo) {
      const { b1, b2, b3, b4, widths, ups, i, j, k, l } = bestCombo;
      let batchCycles = Infinity;

      if (ups === 3) {
        if (i === j && j === k) {
          batchCycles = Math.floor(b1.remainingRolls / 3);
        } else if (i === j) {
          batchCycles = Math.min(Math.floor(b1.remainingRolls / 2), b3.remainingRolls);
        } else if (j === k) {
          batchCycles = Math.min(b1.remainingRolls, Math.floor(b2.remainingRolls / 2));
        } else {
          batchCycles = Math.min(b1.remainingRolls, b2.remainingRolls, b3.remainingRolls);
        }
      } else if (ups === 4 && b4 !== undefined && l !== undefined) {
        const counts: Record<number, number> = {};
        counts[i] = (counts[i] || 0) + 1;
        counts[j] = (counts[j] || 0) + 1;
        counts[k] = (counts[k] || 0) + 1;
        counts[l] = (counts[l] || 0) + 1;
        for (const [idx, needed] of Object.entries(counts)) {
          const avail = Math.floor(activeBuckets[Number(idx)].remainingRolls / needed);
          if (avail < batchCycles) batchCycles = avail;
        }
      }

      batchCycles = Math.max(1, batchCycles);
      const reqs = ups === 3 ? [b1.req, b2.req, b3.req] : [b1.req, b2.req, b3.req, b4!.req];
      const runLength = b1.length;

      for (let c = 0; c < batchCycles; c++) {
        const plan = generatePS01PlanForJumboCombination(
          widths,
          planIndex++,
          film,
          runLength,
          thickness,
          reqs,
          createdBy,
          1
        );
        plans.push(plan);
      }

      // Deduct used roll quantities
      if (ups === 3) {
        if (i === j && j === k) {
          b1.remainingRolls -= 3 * batchCycles;
        } else if (i === j) {
          b1.remainingRolls -= 2 * batchCycles;
          b3.remainingRolls -= batchCycles;
        } else if (j === k) {
          b1.remainingRolls -= batchCycles;
          b2.remainingRolls -= 2 * batchCycles;
        } else {
          b1.remainingRolls -= batchCycles;
          b2.remainingRolls -= batchCycles;
          b3.remainingRolls -= batchCycles;
        }
      } else if (ups === 4 && l !== undefined) {
        const counts: Record<number, number> = {};
        counts[i] = (counts[i] || 0) + 1;
        counts[j] = (counts[j] || 0) + 1;
        counts[k] = (counts[k] || 0) + 1;
        counts[l] = (counts[l] || 0) + 1;
        for (const [idx, needed] of Object.entries(counts)) {
          activeBuckets[Number(idx)].remainingRolls -= needed * batchCycles;
        }
      }

      activeBuckets = activeBuckets.filter(b => b.remainingRolls > 0);
    } else {
      // 4. Once combinatorial search is exhausted, process all remaining activeBuckets cleanly
      while (activeBuckets.length > 0) {
        const singleBucket = activeBuckets[0];
        const parentDeckleId = singleBucket.req.ps01_parent_deckle_id;
        const feasibilityCuts = singleBucket.req.ps01_feasibility?.ps01_cut_combination;

        // Check if sibling buckets sharing the same parent deckle exist in activeBuckets
        const siblingBuckets = parentDeckleId
          ? activeBuckets.filter(b => b.req.ps01_parent_deckle_id === parentDeckleId)
          : [singleBucket];

        if (siblingBuckets.length > 1 && feasibilityCuts && feasibilityCuts.length > 0) {
          // Map cuts to sibling buckets needing rolls
          const matchedBuckets: JumboDemandBucket[] = [];
          const matchedWidths: number[] = [];
          const tempRemaining = new Map<string, number>();
          for (const b of siblingBuckets) tempRemaining.set(b.id, b.remainingRolls);

          for (const cutW of feasibilityCuts) {
            const match = siblingBuckets.find(b => {
              const rem = tempRemaining.get(b.id) || 0;
              return rem > 0 && Math.abs(b.width - cutW) <= 15;
            });
            if (match) {
              matchedBuckets.push(match);
              matchedWidths.push(cutW);
              tempRemaining.set(match.id, (tempRemaining.get(match.id) || 0) - 1);
            }
          }

          if (matchedBuckets.length > 0) {
            const plan = generatePS01PlanForJumboCombination(
              matchedWidths,
              planIndex++,
              singleBucket.req.film || film,
              singleBucket.length,
              singleBucket.req.thickness_micron || thickness,
              matchedBuckets.map(b => b.req),
              createdBy,
              1
            );
            plans.push(plan);
            for (const mb of matchedBuckets) {
              mb.remainingRolls -= 1;
            }
            activeBuckets = activeBuckets.filter(b => b.remainingRolls > 0);
            continue;
          }
        }

        // Isolated fallback plan: produce ONLY its intended roll count
        for (let r = 0; r < singleBucket.remainingRolls; r++) {
          const singlePlan = generatePS01PlanForJumboCombination(
            [singleBucket.width],
            planIndex++,
            singleBucket.req.film || film,
            singleBucket.length,
            singleBucket.req.thickness_micron || thickness,
            [singleBucket.req],
            createdBy,
            1
          );
          plans.push(singlePlan);
        }
        singleBucket.remainingRolls = 0;
        activeBuckets = activeBuckets.filter(b => b.remainingRolls > 0);
      }
      break;
    }
  }

  // Hard quantity reconciliation guard across campaign:
  // Manufactured jumbo rolls allocated to MSL must equal the demand-backed jumbo rolls required by its MSL requirements.
  const totalManufacturedJumbos = plans.reduce((sum, p) => sum + (p.total_reels || 0), 0);
  const totalRequiredJumbos = requirements.reduce((sum, r) => sum + (r.required_rolls_count || 1), 0);
  if (totalManufacturedJumbos !== totalRequiredJumbos) {
    throw new Error(
      `PS01 Quantity Reconciliation Guard Violation: Campaign manufactured ${totalManufacturedJumbos} jumbo rolls across ${plans.length} plans, but MSL requirements require exactly ${totalRequiredJumbos} jumbo rolls (delta: ${totalManufacturedJumbos - totalRequiredJumbos}).`
    );
  }

  logs.push({
    step: logs.length + 1,
    message: `Generated ${plans.length} optimized PS01 Manufacturing Plan(s) for ${film} jumbo rolls with isolated Factory Sheets. Minimized setups and waste.`,
    type: 'SUCCESS' as const,
    data: { planCount: plans.length },
  });

  return {
    plans,
    film,
    logs,
  };
}

/**
 * Backward compatibility alias
 */
export function generatePS01ManufacturingPlanForJumbos(
  requirements: JumboRequirement[],
  film: string,
  createdBy: string = 'M.USMAN (Planner)'
): {
  plans: SlitterPlan[];
  film: string;
  logs: any[];
} {
  return generatePS01ManufacturingPlansForJumbos(requirements, film, createdBy);
}

/**
 * Phase 6: PS01 Manufacturing Plan Consolidation.
 * Merges identical PS01 setup tickets (same film, deckle, jumbo widths, run length, thickness)
 * into a single setup ticket with summed repetitions / sets to slit.
 */
export function consolidatePS01Plans(plans: SlitterPlan[]): SlitterPlan[] {
  const consolidated: SlitterPlan[] = [];
  const merged = new Set<number>();

  for (let i = 0; i < plans.length; i++) {
    if (merged.has(i)) continue;
    const p1 = plans[i];
    let totalRepetitions = (p1.segments[0]?.repetitions) || 1;

    for (let j = i + 1; j < plans.length; j++) {
      if (merged.has(j)) continue;
      const p2 = plans[j];

      if (
        p1.film === p2.film &&
        p1.thickness_micron === p2.thickness_micron &&
        p1.deckle_mm === p2.deckle_mm &&
        p1.trim_mm === p2.trim_mm &&
        p1.items.length === p2.items.length &&
        p1.items.every((it, idx) => it.width_mm === p2.items[idx].width_mm && it.length_m === p2.items[idx].length_m)
      ) {
        totalRepetitions += (p2.segments[0]?.repetitions) || 1;
        merged.add(j);
      }
    }

    const singleRep = (p1.segments[0]?.repetitions) || 1;
    const updatedItems = p1.items.map(it => {
      const singleW = (it.total_weight_kg || 0) / singleRep;
      return {
        ...it,
        reels: totalRepetitions,
        total_weight_kg: Number((singleW * totalRepetitions).toFixed(2)),
      };
    });

    const updatedPlan: SlitterPlan = {
      ...p1,
      segments: [{
        ...p1.segments[0],
        repetitions: totalRepetitions,
        start_pack: 1,
        end_pack: totalRepetitions,
        items: updatedItems,
      }],
      items: updatedItems,
    };

    consolidated.push(updatedPlan);
  }

  return consolidated;
}


